// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: feedaggregator/clp/api.proto

package clp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_feedaggregator_clp_api_proto protoreflect.FileDescriptor

const file_feedaggregator_clp_api_proto_rawDesc = "" +
	"\n" +
	"\x1cfeedaggregator/clp/api.proto\x12\x11clpfeedaggregator\x1a feedaggregator/clp/request.proto\x1a!feedaggregator/clp/response.proto2\x7f\n" +
	"\x0eClpFeedHandler\x12m\n" +
	"\fFetchClpFeed\x12,.clpfeedaggregator.CatalogListingPageRequest\x1a-.clpfeedaggregator.CatalogListingPageResponse\"\x00BE\n" +
	"4com.meesho.ml.feedaggregator.clpclient.grpc.servicesP\x01Z\v../grpc/clpb\x06proto3"

var file_feedaggregator_clp_api_proto_goTypes = []any{
	(*CatalogListingPageRequest)(nil),  // 0: clpfeedaggregator.CatalogListingPageRequest
	(*CatalogListingPageResponse)(nil), // 1: clpfeedaggregator.CatalogListingPageResponse
}
var file_feedaggregator_clp_api_proto_depIdxs = []int32{
	0, // 0: clpfeedaggregator.ClpFeedHandler.FetchClpFeed:input_type -> clpfeedaggregator.CatalogListingPageRequest
	1, // 1: clpfeedaggregator.ClpFeedHandler.FetchClpFeed:output_type -> clpfeedaggregator.CatalogListingPageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feedaggregator_clp_api_proto_init() }
func file_feedaggregator_clp_api_proto_init() {
	if File_feedaggregator_clp_api_proto != nil {
		return
	}
	file_feedaggregator_clp_request_proto_init()
	file_feedaggregator_clp_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedaggregator_clp_api_proto_rawDesc), len(file_feedaggregator_clp_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedaggregator_clp_api_proto_goTypes,
		DependencyIndexes: file_feedaggregator_clp_api_proto_depIdxs,
	}.Build()
	File_feedaggregator_clp_api_proto = out.File
	file_feedaggregator_clp_api_proto_goTypes = nil
	file_feedaggregator_clp_api_proto_depIdxs = nil
}
