// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: feedaggregator/clp/api.proto

package clp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClpFeedHandler_FetchClpFeed_FullMethodName = "/clpfeedaggregator.ClpFeedHandler/FetchClpFeed"
)

// ClpFeedHandlerClient is the client API for ClpFeedHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClpFeedHandlerClient interface {
	FetchClpFeed(ctx context.Context, in *CatalogListingPageRequest, opts ...grpc.CallOption) (*CatalogListingPageResponse, error)
}

type clpFeedHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewClpFeedHandlerClient(cc grpc.ClientConnInterface) ClpFeedHandlerClient {
	return &clpFeedHandlerClient{cc}
}

func (c *clpFeedHandlerClient) FetchClpFeed(ctx context.Context, in *CatalogListingPageRequest, opts ...grpc.CallOption) (*CatalogListingPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogListingPageResponse)
	err := c.cc.Invoke(ctx, ClpFeedHandler_FetchClpFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClpFeedHandlerServer is the server API for ClpFeedHandler service.
// All implementations must embed UnimplementedClpFeedHandlerServer
// for forward compatibility.
type ClpFeedHandlerServer interface {
	FetchClpFeed(context.Context, *CatalogListingPageRequest) (*CatalogListingPageResponse, error)
	mustEmbedUnimplementedClpFeedHandlerServer()
}

// UnimplementedClpFeedHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClpFeedHandlerServer struct{}

func (UnimplementedClpFeedHandlerServer) FetchClpFeed(context.Context, *CatalogListingPageRequest) (*CatalogListingPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchClpFeed not implemented")
}
func (UnimplementedClpFeedHandlerServer) mustEmbedUnimplementedClpFeedHandlerServer() {}
func (UnimplementedClpFeedHandlerServer) testEmbeddedByValue()                        {}

// UnsafeClpFeedHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClpFeedHandlerServer will
// result in compilation errors.
type UnsafeClpFeedHandlerServer interface {
	mustEmbedUnimplementedClpFeedHandlerServer()
}

func RegisterClpFeedHandlerServer(s grpc.ServiceRegistrar, srv ClpFeedHandlerServer) {
	// If the following call pancis, it indicates UnimplementedClpFeedHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClpFeedHandler_ServiceDesc, srv)
}

func _ClpFeedHandler_FetchClpFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CatalogListingPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClpFeedHandlerServer).FetchClpFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClpFeedHandler_FetchClpFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClpFeedHandlerServer).FetchClpFeed(ctx, req.(*CatalogListingPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClpFeedHandler_ServiceDesc is the grpc.ServiceDesc for ClpFeedHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClpFeedHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clpfeedaggregator.ClpFeedHandler",
	HandlerType: (*ClpFeedHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchClpFeed",
			Handler:    _ClpFeedHandler_FetchClpFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedaggregator/clp/api.proto",
}
