// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: feedaggregator/clp/request.proto

package clp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatalogListingPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        *Filter                `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogListingPageRequest) Reset() {
	*x = CatalogListingPageRequest{}
	mi := &file_feedaggregator_clp_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogListingPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogListingPageRequest) ProtoMessage() {}

func (x *CatalogListingPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_clp_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogListingPageRequest.ProtoReflect.Descriptor instead.
func (*CatalogListingPageRequest) Descriptor() ([]byte, []int) {
	return file_feedaggregator_clp_request_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogListingPageRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *CatalogListingPageRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CatalogListingPageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CatalogListingPageRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Filter struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SelectedFilters      []string               `protobuf:"bytes,1,rep,name=selected_filters,proto3" json:"selected_filters,omitempty"`
	SortOption           *SortOption            `protobuf:"bytes,2,opt,name=sort_option,proto3" json:"sort_option,omitempty"`
	SessionState         string                 `protobuf:"bytes,3,opt,name=session_state,proto3" json:"session_state,omitempty"`
	CatalogListingPageId int32                  `protobuf:"varint,4,opt,name=catalog_listing_page_id,proto3" json:"catalog_listing_page_id,omitempty"`
	Payload              string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_feedaggregator_clp_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_clp_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_feedaggregator_clp_request_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetSelectedFilters() []string {
	if x != nil {
		return x.SelectedFilters
	}
	return nil
}

func (x *Filter) GetSortOption() *SortOption {
	if x != nil {
		return x.SortOption
	}
	return nil
}

func (x *Filter) GetSessionState() string {
	if x != nil {
		return x.SessionState
	}
	return ""
}

func (x *Filter) GetCatalogListingPageId() int32 {
	if x != nil {
		return x.CatalogListingPageId
	}
	return 0
}

func (x *Filter) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type SortOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortBy        string                 `protobuf:"bytes,1,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SortOrder     string                 `protobuf:"bytes,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Selected      bool                   `protobuf:"varint,4,opt,name=selected,proto3" json:"selected,omitempty"`
	Default       bool                   `protobuf:"varint,5,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortOption) Reset() {
	*x = SortOption{}
	mi := &file_feedaggregator_clp_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortOption) ProtoMessage() {}

func (x *SortOption) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_clp_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortOption.ProtoReflect.Descriptor instead.
func (*SortOption) Descriptor() ([]byte, []int) {
	return file_feedaggregator_clp_request_proto_rawDescGZIP(), []int{2}
}

func (x *SortOption) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SortOption) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SortOption) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *SortOption) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *SortOption) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

var File_feedaggregator_clp_request_proto protoreflect.FileDescriptor

const file_feedaggregator_clp_request_proto_rawDesc = "" +
	"\n" +
	" feedaggregator/clp/request.proto\x12\x11clpfeedaggregator\"\x94\x01\n" +
	"\x19CatalogListingPageRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x121\n" +
	"\x06filter\x18\x04 \x01(\v2\x19.clpfeedaggregator.FilterR\x06filter\"\xef\x01\n" +
	"\x06Filter\x12*\n" +
	"\x10selected_filters\x18\x01 \x03(\tR\x10selected_filters\x12?\n" +
	"\vsort_option\x18\x02 \x01(\v2\x1d.clpfeedaggregator.SortOptionR\vsort_option\x12$\n" +
	"\rsession_state\x18\x03 \x01(\tR\rsession_state\x128\n" +
	"\x17catalog_listing_page_id\x18\x04 \x01(\x05R\x17catalog_listing_page_id\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\"\x9d\x01\n" +
	"\n" +
	"SortOption\x12\x17\n" +
	"\asort_by\x18\x01 \x01(\tR\x06sortBy\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\tR\tsortOrder\x12\x1a\n" +
	"\bselected\x18\x04 \x01(\bR\bselected\x12\x18\n" +
	"\adefault\x18\x05 \x01(\bR\adefaultBA\n" +
	"0com.meesho.ml.feedaggregator.clpclient.grpc.dtosP\x01Z\v../grpc/clpb\x06proto3"

var (
	file_feedaggregator_clp_request_proto_rawDescOnce sync.Once
	file_feedaggregator_clp_request_proto_rawDescData []byte
)

func file_feedaggregator_clp_request_proto_rawDescGZIP() []byte {
	file_feedaggregator_clp_request_proto_rawDescOnce.Do(func() {
		file_feedaggregator_clp_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedaggregator_clp_request_proto_rawDesc), len(file_feedaggregator_clp_request_proto_rawDesc)))
	})
	return file_feedaggregator_clp_request_proto_rawDescData
}

var file_feedaggregator_clp_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_feedaggregator_clp_request_proto_goTypes = []any{
	(*CatalogListingPageRequest)(nil), // 0: clpfeedaggregator.CatalogListingPageRequest
	(*Filter)(nil),                    // 1: clpfeedaggregator.Filter
	(*SortOption)(nil),                // 2: clpfeedaggregator.SortOption
}
var file_feedaggregator_clp_request_proto_depIdxs = []int32{
	1, // 0: clpfeedaggregator.CatalogListingPageRequest.filter:type_name -> clpfeedaggregator.Filter
	2, // 1: clpfeedaggregator.Filter.sort_option:type_name -> clpfeedaggregator.SortOption
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_feedaggregator_clp_request_proto_init() }
func file_feedaggregator_clp_request_proto_init() {
	if File_feedaggregator_clp_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedaggregator_clp_request_proto_rawDesc), len(file_feedaggregator_clp_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedaggregator_clp_request_proto_goTypes,
		DependencyIndexes: file_feedaggregator_clp_request_proto_depIdxs,
		MessageInfos:      file_feedaggregator_clp_request_proto_msgTypes,
	}.Build()
	File_feedaggregator_clp_request_proto = out.File
	file_feedaggregator_clp_request_proto_goTypes = nil
	file_feedaggregator_clp_request_proto_depIdxs = nil
}
