// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: foryou/v2/api.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_foryou_v2_api_proto protoreflect.FileDescriptor

const file_foryou_v2_api_proto_rawDesc = "" +
	"\n" +
	"\x13foryou/v2/api.proto\x1a\x17foryou/v2/request.proto\x1a\x18foryou/v2/response.proto2g\n" +
	"\x0fFyFeedHandlerV2\x12T\n" +
	"\x11FetchForYouFeedV2\x12\x1c.request.ForYouFeedRequestV2\x1a\x1f.foryou.v2.ForYouFeedResponseV2\"\x00B\aZ\x05../v2b\x06proto3"

var file_foryou_v2_api_proto_goTypes = []any{
	(*ForYouFeedRequestV2)(nil),  // 0: request.ForYouFeedRequestV2
	(*ForYouFeedResponseV2)(nil), // 1: foryou.v2.ForYouFeedResponseV2
}
var file_foryou_v2_api_proto_depIdxs = []int32{
	0, // 0: FyFeedHandlerV2.FetchForYouFeedV2:input_type -> request.ForYouFeedRequestV2
	1, // 1: FyFeedHandlerV2.FetchForYouFeedV2:output_type -> foryou.v2.ForYouFeedResponseV2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foryou_v2_api_proto_init() }
func file_foryou_v2_api_proto_init() {
	if File_foryou_v2_api_proto != nil {
		return
	}
	file_foryou_v2_request_proto_init()
	file_foryou_v2_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foryou_v2_api_proto_rawDesc), len(file_foryou_v2_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foryou_v2_api_proto_goTypes,
		DependencyIndexes: file_foryou_v2_api_proto_depIdxs,
	}.Build()
	File_foryou_v2_api_proto = out.File
	file_foryou_v2_api_proto_goTypes = nil
	file_foryou_v2_api_proto_depIdxs = nil
}