// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: foryou/v2/api.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FyFeedHandlerV2_FetchForYouFeedV2_FullMethodName = "/FyFeedHandlerV2/FetchForYouFeedV2"
)

// FyFeedHandlerV2Client is the client API for FyFeedHandlerV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FyFeedHandlerV2Client interface {
	FetchForYouFeedV2(ctx context.Context, in *ForYouFeedRequestV2, opts ...grpc.CallOption) (*ForYouFeedResponseV2, error)
}

type fyFeedHandlerV2Client struct {
	cc grpc.ClientConnInterface
}

func NewFyFeedHandlerV2Client(cc grpc.ClientConnInterface) FyFeedHandlerV2Client {
	return &fyFeedHandlerV2Client{cc}
}

func (c *fyFeedHandlerV2Client) FetchForYouFeedV2(ctx context.Context, in *ForYouFeedRequestV2, opts ...grpc.CallOption) (*ForYouFeedResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForYouFeedResponseV2)
	err := c.cc.Invoke(ctx, FyFeedHandlerV2_FetchForYouFeedV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FyFeedHandlerV2Server is the server API for FyFeedHandlerV2 service.
// All implementations must embed UnimplementedFyFeedHandlerV2Server
// for forward compatibility.
type FyFeedHandlerV2Server interface {
	FetchForYouFeedV2(context.Context, *ForYouFeedRequestV2) (*ForYouFeedResponseV2, error)
	mustEmbedUnimplementedFyFeedHandlerV2Server()
}

// UnimplementedFyFeedHandlerV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFyFeedHandlerV2Server struct{}

func (UnimplementedFyFeedHandlerV2Server) FetchForYouFeedV2(context.Context, *ForYouFeedRequestV2) (*ForYouFeedResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchForYouFeedV2 not implemented")
}
func (UnimplementedFyFeedHandlerV2Server) mustEmbedUnimplementedFyFeedHandlerV2Server() {}
func (UnimplementedFyFeedHandlerV2Server) testEmbeddedByValue()                         {}

// UnsafeFyFeedHandlerV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FyFeedHandlerV2Server will
// result in compilation errors.
type UnsafeFyFeedHandlerV2Server interface {
	mustEmbedUnimplementedFyFeedHandlerV2Server()
}

func RegisterFyFeedHandlerV2Server(s grpc.ServiceRegistrar, srv FyFeedHandlerV2Server) {
	// If the following call pancis, it indicates UnimplementedFyFeedHandlerV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FyFeedHandlerV2_ServiceDesc, srv)
}

func _FyFeedHandlerV2_FetchForYouFeedV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForYouFeedRequestV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FyFeedHandlerV2Server).FetchForYouFeedV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FyFeedHandlerV2_FetchForYouFeedV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FyFeedHandlerV2Server).FetchForYouFeedV2(ctx, req.(*ForYouFeedRequestV2))
	}
	return interceptor(ctx, in, info, handler)
}

// FyFeedHandlerV2_ServiceDesc is the grpc.ServiceDesc for FyFeedHandlerV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FyFeedHandlerV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FyFeedHandlerV2",
	HandlerType: (*FyFeedHandlerV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchForYouFeedV2",
			Handler:    _FyFeedHandlerV2_FetchForYouFeedV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foryou/v2/api.proto",
}