// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: foryou/v2/request.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForYouFeedRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	FeedContext   string                 `protobuf:"bytes,4,opt,name=feed_context,json=feedContext,proto3" json:"feed_context,omitempty"`
	Filter        *FilterV2              `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	CollectionId  int64                  `protobuf:"varint,6,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Origin        string                 `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForYouFeedRequestV2) Reset() {
	*x = ForYouFeedRequestV2{}
	mi := &file_foryou_v2_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForYouFeedRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForYouFeedRequestV2) ProtoMessage() {}

func (x *ForYouFeedRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_foryou_v2_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForYouFeedRequestV2.ProtoReflect.Descriptor instead.
func (*ForYouFeedRequestV2) Descriptor() ([]byte, []int) {
	return file_foryou_v2_request_proto_rawDescGZIP(), []int{0}
}

func (x *ForYouFeedRequestV2) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ForYouFeedRequestV2) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ForYouFeedRequestV2) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ForYouFeedRequestV2) GetFeedContext() string {
	if x != nil {
		return x.FeedContext
	}
	return ""
}

func (x *ForYouFeedRequestV2) GetFilter() *FilterV2 {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ForYouFeedRequestV2) GetCollectionId() int64 {
	if x != nil {
		return x.CollectionId
	}
	return 0
}

func (x *ForYouFeedRequestV2) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type FilterV2 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SelectedFilters []string               `protobuf:"bytes,1,rep,name=selected_filters,json=selectedFilters,proto3" json:"selected_filters,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SortOption      *SortOptionV2          `protobuf:"bytes,3,opt,name=sort_option,json=sortOption,proto3" json:"sort_option,omitempty"`
	SessionState    string                 `protobuf:"bytes,4,opt,name=session_state,json=sessionState,proto3" json:"session_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FilterV2) Reset() {
	*x = FilterV2{}
	mi := &file_foryou_v2_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterV2) ProtoMessage() {}

func (x *FilterV2) ProtoReflect() protoreflect.Message {
	mi := &file_foryou_v2_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterV2.ProtoReflect.Descriptor instead.
func (*FilterV2) Descriptor() ([]byte, []int) {
	return file_foryou_v2_request_proto_rawDescGZIP(), []int{1}
}

func (x *FilterV2) GetSelectedFilters() []string {
	if x != nil {
		return x.SelectedFilters
	}
	return nil
}

func (x *FilterV2) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FilterV2) GetSortOption() *SortOptionV2 {
	if x != nil {
		return x.SortOption
	}
	return nil
}

func (x *FilterV2) GetSessionState() string {
	if x != nil {
		return x.SessionState
	}
	return ""
}

type SortOptionV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SortBy        string                 `protobuf:"bytes,1,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SortOrder     string                 `protobuf:"bytes,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Selected      bool                   `protobuf:"varint,4,opt,name=selected,proto3" json:"selected,omitempty"`
	Default       bool                   `protobuf:"varint,5,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortOptionV2) Reset() {
	*x = SortOptionV2{}
	mi := &file_foryou_v2_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortOptionV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortOptionV2) ProtoMessage() {}

func (x *SortOptionV2) ProtoReflect() protoreflect.Message {
	mi := &file_foryou_v2_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortOptionV2.ProtoReflect.Descriptor instead.
func (*SortOptionV2) Descriptor() ([]byte, []int) {
	return file_foryou_v2_request_proto_rawDescGZIP(), []int{2}
}

func (x *SortOptionV2) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *SortOptionV2) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SortOptionV2) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *SortOptionV2) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *SortOptionV2) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

var File_foryou_v2_request_proto protoreflect.FileDescriptor

const file_foryou_v2_request_proto_rawDesc = "" +
	"\n" +
	"\x17foryou/v2/request.proto\x12\arequest\"\xe6\x01\n" +
	"\x13ForYouFeedRequestV2\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12!\n" +
	"\ffeed_context\x18\x04 \x01(\tR\vfeedContext\x12)\n" +
	"\x06filter\x18\x05 \x01(\v2\x11.request.FilterV2R\x06filter\x12#\n" +
	"\rcollection_id\x18\x06 \x01(\x03R\fcollectionId\x12\x16\n" +
	"\x06origin\x18\a \x01(\tR\x06origin\"\xa6\x01\n" +
	"\bFilterV2\x12)\n" +
	"\x10selected_filters\x18\x01 \x03(\tR\x0fselectedFilters\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x126\n" +
	"\vsort_option\x18\x03 \x01(\v2\x15.request.SortOptionV2R\n" +
	"sortOption\x12#\n" +
	"\rsession_state\x18\x04 \x01(\tR\fsessionState\"\x9f\x01\n" +
	"\fSortOptionV2\x12\x17\n" +
	"\asort_by\x18\x01 \x01(\tR\x06sortBy\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\tR\tsortOrder\x12\x1a\n" +
	"\bselected\x18\x04 \x01(\bR\bselected\x12\x18\n" +
	"\adefault\x18\x05 \x01(\bR\adefaultB\aZ\x05../v2b\x06proto3"

var (
	file_foryou_v2_request_proto_rawDescOnce sync.Once
	file_foryou_v2_request_proto_rawDescData []byte
)

func file_foryou_v2_request_proto_rawDescGZIP() []byte {
	file_foryou_v2_request_proto_rawDescOnce.Do(func() {
		file_foryou_v2_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foryou_v2_request_proto_rawDesc), len(file_foryou_v2_request_proto_rawDesc)))
	})
	return file_foryou_v2_request_proto_rawDescData
}

var file_foryou_v2_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_foryou_v2_request_proto_goTypes = []any{
	(*ForYouFeedRequestV2)(nil), // 0: request.ForYouFeedRequestV2
	(*FilterV2)(nil),            // 1: request.FilterV2
	(*SortOptionV2)(nil),        // 2: request.SortOptionV2
}
var file_foryou_v2_request_proto_depIdxs = []int32{
	1, // 0: request.ForYouFeedRequestV2.filter:type_name -> request.FilterV2
	2, // 1: request.FilterV2.sort_option:type_name -> request.SortOptionV2
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_foryou_v2_request_proto_init() }
func file_foryou_v2_request_proto_init() {
	if File_foryou_v2_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foryou_v2_request_proto_rawDesc), len(file_foryou_v2_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foryou_v2_request_proto_goTypes,
		DependencyIndexes: file_foryou_v2_request_proto_depIdxs,
		MessageInfos:      file_foryou_v2_request_proto_msgTypes,
	}.Build()
	File_foryou_v2_request_proto = out.File
	file_foryou_v2_request_proto_goTypes = nil
	file_foryou_v2_request_proto_depIdxs = nil
}