// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: feedaggregator/pdp/api.proto

package pdp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PdpFeedHandler_FetchPdpFeed_FullMethodName = "/pdpfeedaggregator.PdpFeedHandler/FetchPdpFeed"
)

// PdpFeedHandlerClient is the client API for PdpFeedHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdpFeedHandlerClient interface {
	FetchPdpFeed(ctx context.Context, in *RecommendationsRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
}

type pdpFeedHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewPdpFeedHandlerClient(cc grpc.ClientConnInterface) PdpFeedHandlerClient {
	return &pdpFeedHandlerClient{cc}
}

func (c *pdpFeedHandlerClient) FetchPdpFeed(ctx context.Context, in *RecommendationsRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, PdpFeedHandler_FetchPdpFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdpFeedHandlerServer is the server API for PdpFeedHandler service.
// All implementations must embed UnimplementedPdpFeedHandlerServer
// for forward compatibility.
type PdpFeedHandlerServer interface {
	FetchPdpFeed(context.Context, *RecommendationsRequest) (*RecommendationResponse, error)
	mustEmbedUnimplementedPdpFeedHandlerServer()
}

// UnimplementedPdpFeedHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPdpFeedHandlerServer struct{}

func (UnimplementedPdpFeedHandlerServer) FetchPdpFeed(context.Context, *RecommendationsRequest) (*RecommendationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchPdpFeed not implemented")
}
func (UnimplementedPdpFeedHandlerServer) mustEmbedUnimplementedPdpFeedHandlerServer() {}
func (UnimplementedPdpFeedHandlerServer) testEmbeddedByValue()                        {}

// UnsafePdpFeedHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdpFeedHandlerServer will
// result in compilation errors.
type UnsafePdpFeedHandlerServer interface {
	mustEmbedUnimplementedPdpFeedHandlerServer()
}

func RegisterPdpFeedHandlerServer(s grpc.ServiceRegistrar, srv PdpFeedHandlerServer) {
	// If the following call pancis, it indicates UnimplementedPdpFeedHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PdpFeedHandler_ServiceDesc, srv)
}

func _PdpFeedHandler_FetchPdpFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdpFeedHandlerServer).FetchPdpFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdpFeedHandler_FetchPdpFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdpFeedHandlerServer).FetchPdpFeed(ctx, req.(*RecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PdpFeedHandler_ServiceDesc is the grpc.ServiceDesc for PdpFeedHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdpFeedHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdpfeedaggregator.PdpFeedHandler",
	HandlerType: (*PdpFeedHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchPdpFeed",
			Handler:    _PdpFeedHandler_FetchPdpFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedaggregator/pdp/api.proto",
}
