// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: feedaggregator/pdp/request.proto

package pdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMetadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WidgetPosition      int32                  `protobuf:"varint,1,opt,name=widget_position,json=widgetPosition,proto3" json:"widget_position,omitempty"`
	Source              string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	SessionId           string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetGroupMetadata *structpb.Struct       `protobuf:"bytes,4,opt,name=widget_group_metadata,json=widgetGroupMetadata,proto3" json:"widget_group_metadata,omitempty"`
	Theme               string                 `protobuf:"bytes,5,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestMetadata) Reset() {
	*x = RequestMetadata{}
	mi := &file_feedaggregator_pdp_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetadata) ProtoMessage() {}

func (x *RequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetadata.ProtoReflect.Descriptor instead.
func (*RequestMetadata) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_request_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetadata) GetWidgetPosition() int32 {
	if x != nil {
		return x.WidgetPosition
	}
	return 0
}

func (x *RequestMetadata) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RequestMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestMetadata) GetWidgetGroupMetadata() *structpb.Struct {
	if x != nil {
		return x.WidgetGroupMetadata
	}
	return nil
}

func (x *RequestMetadata) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type RecommendationsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cursor           string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Offset           int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit            int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	FeedType         string                 `protobuf:"bytes,4,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`
	FeedContext      string                 `protobuf:"bytes,5,opt,name=feed_context,json=feedContext,proto3" json:"feed_context,omitempty"`
	CatalogId        int32                  `protobuf:"varint,6,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`                          // [required=true]
	SubSubCategoryId int32                  `protobuf:"varint,7,opt,name=sub_sub_category_id,json=subSubCategoryId,proto3" json:"sub_sub_category_id,omitempty"` // [(validate.rules).int32.gt = 0]
	ProductId        int32                  `protobuf:"varint,8,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Metadata         *RequestMetadata       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecommendationsRequest) Reset() {
	*x = RecommendationsRequest{}
	mi := &file_feedaggregator_pdp_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsRequest) ProtoMessage() {}

func (x *RecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsRequest.ProtoReflect.Descriptor instead.
func (*RecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_request_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *RecommendationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecommendationsRequest) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

func (x *RecommendationsRequest) GetFeedContext() string {
	if x != nil {
		return x.FeedContext
	}
	return ""
}

func (x *RecommendationsRequest) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *RecommendationsRequest) GetSubSubCategoryId() int32 {
	if x != nil {
		return x.SubSubCategoryId
	}
	return 0
}

func (x *RecommendationsRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RecommendationsRequest) GetMetadata() *RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_feedaggregator_pdp_request_proto protoreflect.FileDescriptor

const file_feedaggregator_pdp_request_proto_rawDesc = "" +
	"\n" +
	" feedaggregator/pdp/request.proto\x12\x11pdpfeedaggregator\x1a\x1cgoogle/protobuf/struct.proto\"\xd4\x01\n" +
	"\x0fRequestMetadata\x12'\n" +
	"\x0fwidget_position\x18\x01 \x01(\x05R\x0ewidgetPosition\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12K\n" +
	"\x15widget_group_metadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x13widgetGroupMetadata\x12\x14\n" +
	"\x05theme\x18\x05 \x01(\tR\x05theme\"\xcb\x02\n" +
	"\x16RecommendationsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tfeed_type\x18\x04 \x01(\tR\bfeedType\x12!\n" +
	"\ffeed_context\x18\x05 \x01(\tR\vfeedContext\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x06 \x01(\x05R\tcatalogId\x12-\n" +
	"\x13sub_sub_category_id\x18\a \x01(\x05R\x10subSubCategoryId\x12\x1d\n" +
	"\n" +
	"product_id\x18\b \x01(\x05R\tproductId\x12>\n" +
	"\bmetadata\x18\t \x01(\v2\".pdpfeedaggregator.RequestMetadataR\bmetadataB<\n" +
	"0com.meesho.ml.feedaggregator.pdpclient.grpc.dtosP\x01Z\x06../pdpb\x06proto3"

var (
	file_feedaggregator_pdp_request_proto_rawDescOnce sync.Once
	file_feedaggregator_pdp_request_proto_rawDescData []byte
)

func file_feedaggregator_pdp_request_proto_rawDescGZIP() []byte {
	file_feedaggregator_pdp_request_proto_rawDescOnce.Do(func() {
		file_feedaggregator_pdp_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedaggregator_pdp_request_proto_rawDesc), len(file_feedaggregator_pdp_request_proto_rawDesc)))
	})
	return file_feedaggregator_pdp_request_proto_rawDescData
}

var file_feedaggregator_pdp_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_feedaggregator_pdp_request_proto_goTypes = []any{
	(*RequestMetadata)(nil),        // 0: pdpfeedaggregator.RequestMetadata
	(*RecommendationsRequest)(nil), // 1: pdpfeedaggregator.RecommendationsRequest
	(*structpb.Struct)(nil),        // 2: google.protobuf.Struct
}
var file_feedaggregator_pdp_request_proto_depIdxs = []int32{
	2, // 0: pdpfeedaggregator.RequestMetadata.widget_group_metadata:type_name -> google.protobuf.Struct
	0, // 1: pdpfeedaggregator.RecommendationsRequest.metadata:type_name -> pdpfeedaggregator.RequestMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_feedaggregator_pdp_request_proto_init() }
func file_feedaggregator_pdp_request_proto_init() {
	if File_feedaggregator_pdp_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedaggregator_pdp_request_proto_rawDesc), len(file_feedaggregator_pdp_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedaggregator_pdp_request_proto_goTypes,
		DependencyIndexes: file_feedaggregator_pdp_request_proto_depIdxs,
		MessageInfos:      file_feedaggregator_pdp_request_proto_msgTypes,
	}.Build()
	File_feedaggregator_pdp_request_proto = out.File
	file_feedaggregator_pdp_request_proto_goTypes = nil
	file_feedaggregator_pdp_request_proto_depIdxs = nil
}
