// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: feedaggregator/pdp/response.proto

package pdp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalogs      []*CatalogDTO          `protobuf:"bytes,1,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetCatalogs() []*CatalogDTO {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

func (x *Data) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type RecommendationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Error          string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Catalogs       []*CatalogDTO          `protobuf:"bytes,2,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	UserData       *UserData              `protobuf:"bytes,3,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	Cursor         string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Metadata       *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ViewTemplateId int32                  `protobuf:"varint,6,opt,name=view_template_id,json=viewTemplateId,proto3" json:"view_template_id,omitempty"`
	Data           *Data                  `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecommendationResponse) Reset() {
	*x = RecommendationResponse{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationResponse) ProtoMessage() {}

func (x *RecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationResponse.ProtoReflect.Descriptor instead.
func (*RecommendationResponse) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RecommendationResponse) GetCatalogs() []*CatalogDTO {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

func (x *RecommendationResponse) GetUserData() *UserData {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *RecommendationResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *RecommendationResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RecommendationResponse) GetViewTemplateId() int32 {
	if x != nil {
		return x.ViewTemplateId
	}
	return 0
}

func (x *RecommendationResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CatalogDTO struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CatalogAd           *CatalogAd             `protobuf:"bytes,2,opt,name=catalog_ad,proto3" json:"catalog_ad,omitempty"`
	HeroPid             int64                  `protobuf:"varint,3,opt,name=hero_pid,proto3" json:"hero_pid,omitempty"`
	ReplaceableCatalogs []*ReplaceableCatalog  `protobuf:"bytes,4,rep,name=replaceable_catalogs,proto3" json:"replaceable_catalogs,omitempty"`
	Source              string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Tracker             *Tracker               `protobuf:"bytes,6,opt,name=tracker,proto3" json:"tracker,omitempty"`
	CatalogMatchType    string                 `protobuf:"bytes,7,opt,name=catalog_match_type,proto3" json:"catalog_match_type,omitempty"`
	Event               *Event                 `protobuf:"bytes,8,opt,name=event,proto3" json:"event,omitempty"`
	ReelData            *ReelData              `protobuf:"bytes,9,opt,name=reel_data,proto3" json:"reel_data,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CatalogDTO) Reset() {
	*x = CatalogDTO{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogDTO) ProtoMessage() {}

func (x *CatalogDTO) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogDTO.ProtoReflect.Descriptor instead.
func (*CatalogDTO) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{2}
}

func (x *CatalogDTO) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CatalogDTO) GetCatalogAd() *CatalogAd {
	if x != nil {
		return x.CatalogAd
	}
	return nil
}

func (x *CatalogDTO) GetHeroPid() int64 {
	if x != nil {
		return x.HeroPid
	}
	return 0
}

func (x *CatalogDTO) GetReplaceableCatalogs() []*ReplaceableCatalog {
	if x != nil {
		return x.ReplaceableCatalogs
	}
	return nil
}

func (x *CatalogDTO) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CatalogDTO) GetTracker() *Tracker {
	if x != nil {
		return x.Tracker
	}
	return nil
}

func (x *CatalogDTO) GetCatalogMatchType() string {
	if x != nil {
		return x.CatalogMatchType
	}
	return ""
}

func (x *CatalogDTO) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CatalogDTO) GetReelData() *ReelData {
	if x != nil {
		return x.ReelData
	}
	return nil
}

type ReplaceableCatalog struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CatalogId        int32                  `protobuf:"varint,1,opt,name=catalog_id,proto3" json:"catalog_id,omitempty"`
	ProductId        int32                  `protobuf:"varint,2,opt,name=product_id,proto3" json:"product_id,omitempty"`
	Tracker          *Tracker               `protobuf:"bytes,3,opt,name=tracker,proto3" json:"tracker,omitempty"`
	CatalogMatchType string                 `protobuf:"bytes,4,opt,name=catalog_match_type,proto3" json:"catalog_match_type,omitempty"`
	OByVDelta        float64                `protobuf:"fixed64,5,opt,name=o_by_v_delta,proto3" json:"o_by_v_delta,omitempty"`
	Weight           float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Strategy         string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Event            *Event                 `protobuf:"bytes,8,opt,name=event,proto3" json:"event,omitempty"`
	AdsMetadata      string                 `protobuf:"bytes,9,opt,name=ads_metadata,proto3" json:"ads_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReplaceableCatalog) Reset() {
	*x = ReplaceableCatalog{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceableCatalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceableCatalog) ProtoMessage() {}

func (x *ReplaceableCatalog) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceableCatalog.ProtoReflect.Descriptor instead.
func (*ReplaceableCatalog) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{3}
}

func (x *ReplaceableCatalog) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *ReplaceableCatalog) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ReplaceableCatalog) GetTracker() *Tracker {
	if x != nil {
		return x.Tracker
	}
	return nil
}

func (x *ReplaceableCatalog) GetCatalogMatchType() string {
	if x != nil {
		return x.CatalogMatchType
	}
	return ""
}

func (x *ReplaceableCatalog) GetOByVDelta() float64 {
	if x != nil {
		return x.OByVDelta
	}
	return 0
}

func (x *ReplaceableCatalog) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ReplaceableCatalog) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ReplaceableCatalog) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ReplaceableCatalog) GetAdsMetadata() string {
	if x != nil {
		return x.AdsMetadata
	}
	return ""
}

type CatalogAd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CampaignId    int32                  `protobuf:"varint,3,opt,name=campaign_id,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogAd) Reset() {
	*x = CatalogAd{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogAd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogAd) ProtoMessage() {}

func (x *CatalogAd) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogAd.ProtoReflect.Descriptor instead.
func (*CatalogAd) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{4}
}

func (x *CatalogAd) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CatalogAd) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *CatalogAd) GetCampaignId() int32 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

type Event struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CatalogId          int32                  `protobuf:"varint,1,opt,name=catalog_id,proto3" json:"catalog_id,omitempty"`
	UniqueId           string                 `protobuf:"bytes,2,opt,name=unique_id,proto3" json:"unique_id,omitempty"`
	Meta               *structpb.Struct       `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	SlotPosition       int32                  `protobuf:"varint,4,opt,name=slot_position,proto3" json:"slot_position,omitempty"`
	CatalogServeStatus string                 `protobuf:"bytes,5,opt,name=catalog_serve_status,proto3" json:"catalog_serve_status,omitempty"`
	ProductServeStatus string                 `protobuf:"bytes,6,opt,name=product_serve_status,proto3" json:"product_serve_status,omitempty"`
	ProductId          int32                  `protobuf:"varint,7,opt,name=product_id,proto3" json:"product_id,omitempty"`
	IsProductEvent     bool                   `protobuf:"varint,8,opt,name=is_product_event,proto3" json:"is_product_event,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *Event) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *Event) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Event) GetSlotPosition() int32 {
	if x != nil {
		return x.SlotPosition
	}
	return 0
}

func (x *Event) GetCatalogServeStatus() string {
	if x != nil {
		return x.CatalogServeStatus
	}
	return ""
}

func (x *Event) GetProductServeStatus() string {
	if x != nil {
		return x.ProductServeStatus
	}
	return ""
}

func (x *Event) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Event) GetIsProductEvent() bool {
	if x != nil {
		return x.IsProductEvent
	}
	return false
}

type Metadata struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	StartPos                      int32                  `protobuf:"varint,1,opt,name=start_pos,proto3" json:"start_pos,omitempty"`
	EndPos                        int32                  `protobuf:"varint,2,opt,name=end_pos,proto3" json:"end_pos,omitempty"`
	LocationId                    int64                  `protobuf:"varint,3,opt,name=location_id,proto3" json:"location_id,omitempty"`
	Count                         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	IsSubscribed                  bool                   `protobuf:"varint,5,opt,name=is_subscribed,proto3" json:"is_subscribed,omitempty"`
	ShowWidgets                   bool                   `protobuf:"varint,6,opt,name=show_widgets,proto3" json:"show_widgets,omitempty"`
	CompetitiveMarketplaceEnabled bool                   `protobuf:"varint,7,opt,name=competitive_marketplace_enabled,proto3" json:"competitive_marketplace_enabled,omitempty"`
	FeedAttributes                *structpb.Struct       `protobuf:"bytes,8,opt,name=feed_attributes,proto3" json:"feed_attributes,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *Metadata) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *Metadata) GetLocationId() int64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *Metadata) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Metadata) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

func (x *Metadata) GetShowWidgets() bool {
	if x != nil {
		return x.ShowWidgets
	}
	return false
}

func (x *Metadata) GetCompetitiveMarketplaceEnabled() bool {
	if x != nil {
		return x.CompetitiveMarketplaceEnabled
	}
	return false
}

func (x *Metadata) GetFeedAttributes() *structpb.Struct {
	if x != nil {
		return x.FeedAttributes
	}
	return nil
}

type Tracker struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrackerId       string                 `protobuf:"bytes,1,opt,name=tracker_id,proto3" json:"tracker_id,omitempty"`
	IsProductResult bool                   `protobuf:"varint,2,opt,name=is_product_result,proto3" json:"is_product_result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Tracker) Reset() {
	*x = Tracker{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracker) ProtoMessage() {}

func (x *Tracker) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracker.ProtoReflect.Descriptor instead.
func (*Tracker) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{7}
}

func (x *Tracker) GetTrackerId() string {
	if x != nil {
		return x.TrackerId
	}
	return ""
}

func (x *Tracker) GetIsProductResult() bool {
	if x != nil {
		return x.IsProductResult
	}
	return false
}

type UserData struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	VisibleAudienceIds   []int32                `protobuf:"varint,1,rep,packed,name=visible_audience_ids,proto3" json:"visible_audience_ids,omitempty"`
	NotVisibleAudienceId []int32                `protobuf:"varint,2,rep,packed,name=not_visible_audience_id,proto3" json:"not_visible_audience_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{8}
}

func (x *UserData) GetVisibleAudienceIds() []int32 {
	if x != nil {
		return x.VisibleAudienceIds
	}
	return nil
}

func (x *UserData) GetNotVisibleAudienceId() []int32 {
	if x != nil {
		return x.NotVisibleAudienceId
	}
	return nil
}

type ReelData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tracker         *Tracker               `protobuf:"bytes,2,opt,name=tracker,proto3" json:"tracker,omitempty"`
	Video           *Video                 `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	HeroCatalog     *CatalogInfo           `protobuf:"bytes,4,opt,name=hero_catalog,proto3" json:"hero_catalog,omitempty"`
	CatalogInfo     []*CatalogInfo         `protobuf:"bytes,5,rep,name=catalog_info,proto3" json:"catalog_info,omitempty"`
	UserName        string                 `protobuf:"bytes,6,opt,name=user_name,proto3" json:"user_name,omitempty"`
	Category        string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	FeedType        string                 `protobuf:"bytes,8,opt,name=feed_type,proto3" json:"feed_type,omitempty"`
	LikeCount       int32                  `protobuf:"varint,9,opt,name=like_count,proto3" json:"like_count,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,10,opt,name=profile_image_url,proto3" json:"profile_image_url,omitempty"`
	Gif             string                 `protobuf:"bytes,11,opt,name=gif,proto3" json:"gif,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReelData) Reset() {
	*x = ReelData{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReelData) ProtoMessage() {}

func (x *ReelData) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReelData.ProtoReflect.Descriptor instead.
func (*ReelData) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{9}
}

func (x *ReelData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReelData) GetTracker() *Tracker {
	if x != nil {
		return x.Tracker
	}
	return nil
}

func (x *ReelData) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *ReelData) GetHeroCatalog() *CatalogInfo {
	if x != nil {
		return x.HeroCatalog
	}
	return nil
}

func (x *ReelData) GetCatalogInfo() []*CatalogInfo {
	if x != nil {
		return x.CatalogInfo
	}
	return nil
}

func (x *ReelData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ReelData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ReelData) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

func (x *ReelData) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ReelData) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *ReelData) GetGif() string {
	if x != nil {
		return x.Gif
	}
	return ""
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,proto3" json:"video_url,omitempty"`
	ThumbNailWebp string                 `protobuf:"bytes,2,opt,name=thumb_nail_webp,proto3" json:"thumb_nail_webp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{10}
}

func (x *Video) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Video) GetThumbNailWebp() string {
	if x != nil {
		return x.ThumbNailWebp
	}
	return ""
}

type CatalogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HeroPid       int32                  `protobuf:"varint,2,opt,name=hero_pid,proto3" json:"hero_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogInfo) Reset() {
	*x = CatalogInfo{}
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogInfo) ProtoMessage() {}

func (x *CatalogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_pdp_response_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogInfo.ProtoReflect.Descriptor instead.
func (*CatalogInfo) Descriptor() ([]byte, []int) {
	return file_feedaggregator_pdp_response_proto_rawDescGZIP(), []int{11}
}

func (x *CatalogInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CatalogInfo) GetHeroPid() int32 {
	if x != nil {
		return x.HeroPid
	}
	return 0
}

var File_feedaggregator_pdp_response_proto protoreflect.FileDescriptor

const file_feedaggregator_pdp_response_proto_rawDesc = "" +
	"\n" +
	"!feedaggregator/pdp/response.proto\x12\x11pdpfeedaggregator\x1a\x1cgoogle/protobuf/struct.proto\"Y\n" +
	"\x04Data\x129\n" +
	"\bcatalogs\x18\x01 \x03(\v2\x1d.pdpfeedaggregator.CatalogDTOR\bcatalogs\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\xcb\x02\n" +
	"\x16RecommendationResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x129\n" +
	"\bcatalogs\x18\x02 \x03(\v2\x1d.pdpfeedaggregator.CatalogDTOR\bcatalogs\x128\n" +
	"\tuser_data\x18\x03 \x01(\v2\x1b.pdpfeedaggregator.UserDataR\buserData\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x127\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1b.pdpfeedaggregator.MetadataR\bmetadata\x12(\n" +
	"\x10view_template_id\x18\x06 \x01(\x05R\x0eviewTemplateId\x12+\n" +
	"\x04data\x18\a \x01(\v2\x17.pdpfeedaggregator.DataR\x04data\"\xba\x03\n" +
	"\n" +
	"CatalogDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12<\n" +
	"\n" +
	"catalog_ad\x18\x02 \x01(\v2\x1c.pdpfeedaggregator.CatalogAdR\n" +
	"catalog_ad\x12\x1a\n" +
	"\bhero_pid\x18\x03 \x01(\x03R\bhero_pid\x12Y\n" +
	"\x14replaceable_catalogs\x18\x04 \x03(\v2%.pdpfeedaggregator.ReplaceableCatalogR\x14replaceable_catalogs\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x124\n" +
	"\atracker\x18\x06 \x01(\v2\x1a.pdpfeedaggregator.TrackerR\atracker\x12.\n" +
	"\x12catalog_match_type\x18\a \x01(\tR\x12catalog_match_type\x12.\n" +
	"\x05event\x18\b \x01(\v2\x18.pdpfeedaggregator.EventR\x05event\x129\n" +
	"\treel_data\x18\t \x01(\v2\x1b.pdpfeedaggregator.ReelDataR\treel_data\"\xe6\x02\n" +
	"\x12ReplaceableCatalog\x12\x1e\n" +
	"\n" +
	"catalog_id\x18\x01 \x01(\x05R\n" +
	"catalog_id\x12\x1e\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\n" +
	"product_id\x124\n" +
	"\atracker\x18\x03 \x01(\v2\x1a.pdpfeedaggregator.TrackerR\atracker\x12.\n" +
	"\x12catalog_match_type\x18\x04 \x01(\tR\x12catalog_match_type\x12\"\n" +
	"\fo_by_v_delta\x18\x05 \x01(\x01R\fo_by_v_delta\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\x12.\n" +
	"\x05event\x18\b \x01(\v2\x18.pdpfeedaggregator.EventR\x05event\x12\"\n" +
	"\fads_metadata\x18\t \x01(\tR\fads_metadata\"c\n" +
	"\tCatalogAd\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\x12 \n" +
	"\vcampaign_id\x18\x03 \x01(\x05R\vcampaign_id\"\xcc\x02\n" +
	"\x05Event\x12\x1e\n" +
	"\n" +
	"catalog_id\x18\x01 \x01(\x05R\n" +
	"catalog_id\x12\x1c\n" +
	"\tunique_id\x18\x02 \x01(\tR\tunique_id\x12+\n" +
	"\x04meta\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04meta\x12$\n" +
	"\rslot_position\x18\x04 \x01(\x05R\rslot_position\x122\n" +
	"\x14catalog_serve_status\x18\x05 \x01(\tR\x14catalog_serve_status\x122\n" +
	"\x14product_serve_status\x18\x06 \x01(\tR\x14product_serve_status\x12\x1e\n" +
	"\n" +
	"product_id\x18\a \x01(\x05R\n" +
	"product_id\x12*\n" +
	"\x10is_product_event\x18\b \x01(\bR\x10is_product_event\"\xd1\x02\n" +
	"\bMetadata\x12\x1c\n" +
	"\tstart_pos\x18\x01 \x01(\x05R\tstart_pos\x12\x18\n" +
	"\aend_pos\x18\x02 \x01(\x05R\aend_pos\x12 \n" +
	"\vlocation_id\x18\x03 \x01(\x03R\vlocation_id\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12$\n" +
	"\ris_subscribed\x18\x05 \x01(\bR\ris_subscribed\x12\"\n" +
	"\fshow_widgets\x18\x06 \x01(\bR\fshow_widgets\x12H\n" +
	"\x1fcompetitive_marketplace_enabled\x18\a \x01(\bR\x1fcompetitive_marketplace_enabled\x12A\n" +
	"\x0ffeed_attributes\x18\b \x01(\v2\x17.google.protobuf.StructR\x0ffeed_attributes\"W\n" +
	"\aTracker\x12\x1e\n" +
	"\n" +
	"tracker_id\x18\x01 \x01(\tR\n" +
	"tracker_id\x12,\n" +
	"\x11is_product_result\x18\x02 \x01(\bR\x11is_product_result\"x\n" +
	"\bUserData\x122\n" +
	"\x14visible_audience_ids\x18\x01 \x03(\x05R\x14visible_audience_ids\x128\n" +
	"\x17not_visible_audience_id\x18\x02 \x03(\x05R\x17not_visible_audience_id\"\xc0\x03\n" +
	"\bReelData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x124\n" +
	"\atracker\x18\x02 \x01(\v2\x1a.pdpfeedaggregator.TrackerR\atracker\x12.\n" +
	"\x05video\x18\x03 \x01(\v2\x18.pdpfeedaggregator.VideoR\x05video\x12B\n" +
	"\fhero_catalog\x18\x04 \x01(\v2\x1e.pdpfeedaggregator.CatalogInfoR\fhero_catalog\x12B\n" +
	"\fcatalog_info\x18\x05 \x03(\v2\x1e.pdpfeedaggregator.CatalogInfoR\fcatalog_info\x12\x1c\n" +
	"\tuser_name\x18\x06 \x01(\tR\tuser_name\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x1c\n" +
	"\tfeed_type\x18\b \x01(\tR\tfeed_type\x12\x1e\n" +
	"\n" +
	"like_count\x18\t \x01(\x05R\n" +
	"like_count\x12,\n" +
	"\x11profile_image_url\x18\n" +
	" \x01(\tR\x11profile_image_url\x12\x10\n" +
	"\x03gif\x18\v \x01(\tR\x03gif\"O\n" +
	"\x05Video\x12\x1c\n" +
	"\tvideo_url\x18\x01 \x01(\tR\tvideo_url\x12(\n" +
	"\x0fthumb_nail_webp\x18\x02 \x01(\tR\x0fthumb_nail_webp\"9\n" +
	"\vCatalogInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bhero_pid\x18\x02 \x01(\x05R\bhero_pidB<\n" +
	"0com.meesho.ml.feedaggregator.pdpclient.grpc.dtosP\x01Z\x06../pdpb\x06proto3"

var (
	file_feedaggregator_pdp_response_proto_rawDescOnce sync.Once
	file_feedaggregator_pdp_response_proto_rawDescData []byte
)

func file_feedaggregator_pdp_response_proto_rawDescGZIP() []byte {
	file_feedaggregator_pdp_response_proto_rawDescOnce.Do(func() {
		file_feedaggregator_pdp_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedaggregator_pdp_response_proto_rawDesc), len(file_feedaggregator_pdp_response_proto_rawDesc)))
	})
	return file_feedaggregator_pdp_response_proto_rawDescData
}

var file_feedaggregator_pdp_response_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_feedaggregator_pdp_response_proto_goTypes = []any{
	(*Data)(nil),                   // 0: pdpfeedaggregator.Data
	(*RecommendationResponse)(nil), // 1: pdpfeedaggregator.RecommendationResponse
	(*CatalogDTO)(nil),             // 2: pdpfeedaggregator.CatalogDTO
	(*ReplaceableCatalog)(nil),     // 3: pdpfeedaggregator.ReplaceableCatalog
	(*CatalogAd)(nil),              // 4: pdpfeedaggregator.CatalogAd
	(*Event)(nil),                  // 5: pdpfeedaggregator.Event
	(*Metadata)(nil),               // 6: pdpfeedaggregator.Metadata
	(*Tracker)(nil),                // 7: pdpfeedaggregator.Tracker
	(*UserData)(nil),               // 8: pdpfeedaggregator.UserData
	(*ReelData)(nil),               // 9: pdpfeedaggregator.ReelData
	(*Video)(nil),                  // 10: pdpfeedaggregator.Video
	(*CatalogInfo)(nil),            // 11: pdpfeedaggregator.CatalogInfo
	(*structpb.Struct)(nil),        // 12: google.protobuf.Struct
}
var file_feedaggregator_pdp_response_proto_depIdxs = []int32{
	2,  // 0: pdpfeedaggregator.Data.catalogs:type_name -> pdpfeedaggregator.CatalogDTO
	2,  // 1: pdpfeedaggregator.RecommendationResponse.catalogs:type_name -> pdpfeedaggregator.CatalogDTO
	8,  // 2: pdpfeedaggregator.RecommendationResponse.user_data:type_name -> pdpfeedaggregator.UserData
	6,  // 3: pdpfeedaggregator.RecommendationResponse.metadata:type_name -> pdpfeedaggregator.Metadata
	0,  // 4: pdpfeedaggregator.RecommendationResponse.data:type_name -> pdpfeedaggregator.Data
	4,  // 5: pdpfeedaggregator.CatalogDTO.catalog_ad:type_name -> pdpfeedaggregator.CatalogAd
	3,  // 6: pdpfeedaggregator.CatalogDTO.replaceable_catalogs:type_name -> pdpfeedaggregator.ReplaceableCatalog
	7,  // 7: pdpfeedaggregator.CatalogDTO.tracker:type_name -> pdpfeedaggregator.Tracker
	5,  // 8: pdpfeedaggregator.CatalogDTO.event:type_name -> pdpfeedaggregator.Event
	9,  // 9: pdpfeedaggregator.CatalogDTO.reel_data:type_name -> pdpfeedaggregator.ReelData
	7,  // 10: pdpfeedaggregator.ReplaceableCatalog.tracker:type_name -> pdpfeedaggregator.Tracker
	5,  // 11: pdpfeedaggregator.ReplaceableCatalog.event:type_name -> pdpfeedaggregator.Event
	12, // 12: pdpfeedaggregator.Event.meta:type_name -> google.protobuf.Struct
	12, // 13: pdpfeedaggregator.Metadata.feed_attributes:type_name -> google.protobuf.Struct
	7,  // 14: pdpfeedaggregator.ReelData.tracker:type_name -> pdpfeedaggregator.Tracker
	10, // 15: pdpfeedaggregator.ReelData.video:type_name -> pdpfeedaggregator.Video
	11, // 16: pdpfeedaggregator.ReelData.hero_catalog:type_name -> pdpfeedaggregator.CatalogInfo
	11, // 17: pdpfeedaggregator.ReelData.catalog_info:type_name -> pdpfeedaggregator.CatalogInfo
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_feedaggregator_pdp_response_proto_init() }
func file_feedaggregator_pdp_response_proto_init() {
	if File_feedaggregator_pdp_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedaggregator_pdp_response_proto_rawDesc), len(file_feedaggregator_pdp_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedaggregator_pdp_response_proto_goTypes,
		DependencyIndexes: file_feedaggregator_pdp_response_proto_depIdxs,
		MessageInfos:      file_feedaggregator_pdp_response_proto_msgTypes,
	}.Build()
	File_feedaggregator_pdp_response_proto = out.File
	file_feedaggregator_pdp_response_proto_goTypes = nil
	file_feedaggregator_pdp_response_proto_depIdxs = nil
}
