// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: rv-iop/api.proto

package rv_iop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RvIopService_FetchRvSubstituteExploitFeed_FullMethodName = "/rviop.RvIopService/FetchRvSubstituteExploitFeed"
	RvIopService_FetchRvSubstituteExploreFeed_FullMethodName = "/rviop.RvIopService/FetchRvSubstituteExploreFeed"
	RvIopService_FetchRvSubstituteAdFeed_FullMethodName      = "/rviop.RvIopService/FetchRvSubstituteAdFeed"
	RvIopService_FetchCrossSellWidget_FullMethodName         = "/rviop.RvIopService/FetchCrossSellWidget"
	RvIopService_FetchCrossSellFeed_FullMethodName           = "/rviop.RvIopService/FetchCrossSellFeed"
	RvIopService_FetchRvInteractionsFeed_FullMethodName      = "/rviop.RvIopService/FetchRvInteractionsFeed"
	RvIopService_FetchRvInteractionsWidget_FullMethodName    = "/rviop.RvIopService/FetchRvInteractionsWidget"
	RvIopService_GetComponents_FullMethodName                = "/rviop.RvIopService/GetComponents"
)

// RvIopServiceClient is the client API for RvIopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RvIopServiceClient interface {
	FetchRvSubstituteExploitFeed(ctx context.Context, in *GetRvSubstituteOrganicFeedRequest, opts ...grpc.CallOption) (*GetRvSubstituteOrganicFeedResponse, error)
	FetchRvSubstituteExploreFeed(ctx context.Context, in *GetRvSubstituteCtFeedRequest, opts ...grpc.CallOption) (*GetRvSubstituteCtFeedResponse, error)
	FetchRvSubstituteAdFeed(ctx context.Context, in *GetRvSubstituteAdFeedRequest, opts ...grpc.CallOption) (*GetRvSubstituteAdFeedResponse, error)
	FetchCrossSellWidget(ctx context.Context, in *GetCrossSellWidgetRequest, opts ...grpc.CallOption) (*GetCrossSellWidgetResponse, error)
	FetchCrossSellFeed(ctx context.Context, in *GetCrossSellFeedRequest, opts ...grpc.CallOption) (*GetCrossSellFeedResponse, error)
	FetchRvInteractionsFeed(ctx context.Context, in *GetRvInteractionsFeedRequest, opts ...grpc.CallOption) (*GetRvInteractionsFeedResponse, error)
	FetchRvInteractionsWidget(ctx context.Context, in *GetRvInteractionsWidgetRequest, opts ...grpc.CallOption) (*GetRvInteractionsWidgetResponse, error)
	GetComponents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetComponentsResponse, error)
}

type rvIopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRvIopServiceClient(cc grpc.ClientConnInterface) RvIopServiceClient {
	return &rvIopServiceClient{cc}
}

func (c *rvIopServiceClient) FetchRvSubstituteExploitFeed(ctx context.Context, in *GetRvSubstituteOrganicFeedRequest, opts ...grpc.CallOption) (*GetRvSubstituteOrganicFeedResponse, error) {
	out := new(GetRvSubstituteOrganicFeedResponse)
	err := c.cc.Invoke(ctx, RvIopService_FetchRvSubstituteExploitFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rvIopServiceClient) FetchRvSubstituteExploreFeed(ctx context.Context, in *GetRvSubstituteCtFeedRequest, opts ...grpc.CallOption) (*GetRvSubstituteCtFeedResponse, error) {
	out := new(GetRvSubstituteCtFeedResponse)
	err := c.cc.Invoke(ctx, RvIopService_FetchRvSubstituteExploreFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rvIopServiceClient) FetchRvSubstituteAdFeed(ctx context.Context, in *GetRvSubstituteAdFeedRequest, opts ...grpc.CallOption) (*GetRvSubstituteAdFeedResponse, error) {
	out := new(GetRvSubstituteAdFeedResponse)
	err := c.cc.Invoke(ctx, RvIopService_FetchRvSubstituteAdFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rvIopServiceClient) FetchCrossSellWidget(ctx context.Context, in *GetCrossSellWidgetRequest, opts ...grpc.CallOption) (*GetCrossSellWidgetResponse, error) {
	out := new(GetCrossSellWidgetResponse)
	err := c.cc.Invoke(ctx, RvIopService_FetchCrossSellWidget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rvIopServiceClient) FetchCrossSellFeed(ctx context.Context, in *GetCrossSellFeedRequest, opts ...grpc.CallOption) (*GetCrossSellFeedResponse, error) {
	out := new(GetCrossSellFeedResponse)
	err := c.cc.Invoke(ctx, RvIopService_FetchCrossSellFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rvIopServiceClient) FetchRvInteractionsFeed(ctx context.Context, in *GetRvInteractionsFeedRequest, opts ...grpc.CallOption) (*GetRvInteractionsFeedResponse, error) {
	out := new(GetRvInteractionsFeedResponse)
	err := c.cc.Invoke(ctx, RvIopService_FetchRvInteractionsFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rvIopServiceClient) FetchRvInteractionsWidget(ctx context.Context, in *GetRvInteractionsWidgetRequest, opts ...grpc.CallOption) (*GetRvInteractionsWidgetResponse, error) {
	out := new(GetRvInteractionsWidgetResponse)
	err := c.cc.Invoke(ctx, RvIopService_FetchRvInteractionsWidget_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rvIopServiceClient) GetComponents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetComponentsResponse, error) {
	out := new(GetComponentsResponse)
	err := c.cc.Invoke(ctx, RvIopService_GetComponents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RvIopServiceServer is the server API for RvIopService service.
// All implementations must embed UnimplementedRvIopServiceServer
// for forward compatibility
type RvIopServiceServer interface {
	FetchRvSubstituteExploitFeed(context.Context, *GetRvSubstituteOrganicFeedRequest) (*GetRvSubstituteOrganicFeedResponse, error)
	FetchRvSubstituteExploreFeed(context.Context, *GetRvSubstituteCtFeedRequest) (*GetRvSubstituteCtFeedResponse, error)
	FetchRvSubstituteAdFeed(context.Context, *GetRvSubstituteAdFeedRequest) (*GetRvSubstituteAdFeedResponse, error)
	FetchCrossSellWidget(context.Context, *GetCrossSellWidgetRequest) (*GetCrossSellWidgetResponse, error)
	FetchCrossSellFeed(context.Context, *GetCrossSellFeedRequest) (*GetCrossSellFeedResponse, error)
	FetchRvInteractionsFeed(context.Context, *GetRvInteractionsFeedRequest) (*GetRvInteractionsFeedResponse, error)
	FetchRvInteractionsWidget(context.Context, *GetRvInteractionsWidgetRequest) (*GetRvInteractionsWidgetResponse, error)
	GetComponents(context.Context, *emptypb.Empty) (*GetComponentsResponse, error)
	mustEmbedUnimplementedRvIopServiceServer()
}

// UnimplementedRvIopServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRvIopServiceServer struct {
}

func (UnimplementedRvIopServiceServer) FetchRvSubstituteExploitFeed(context.Context, *GetRvSubstituteOrganicFeedRequest) (*GetRvSubstituteOrganicFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRvSubstituteExploitFeed not implemented")
}
func (UnimplementedRvIopServiceServer) FetchRvSubstituteExploreFeed(context.Context, *GetRvSubstituteCtFeedRequest) (*GetRvSubstituteCtFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRvSubstituteExploreFeed not implemented")
}
func (UnimplementedRvIopServiceServer) FetchRvSubstituteAdFeed(context.Context, *GetRvSubstituteAdFeedRequest) (*GetRvSubstituteAdFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRvSubstituteAdFeed not implemented")
}
func (UnimplementedRvIopServiceServer) FetchCrossSellWidget(context.Context, *GetCrossSellWidgetRequest) (*GetCrossSellWidgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCrossSellWidget not implemented")
}
func (UnimplementedRvIopServiceServer) FetchCrossSellFeed(context.Context, *GetCrossSellFeedRequest) (*GetCrossSellFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCrossSellFeed not implemented")
}
func (UnimplementedRvIopServiceServer) FetchRvInteractionsFeed(context.Context, *GetRvInteractionsFeedRequest) (*GetRvInteractionsFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRvInteractionsFeed not implemented")
}
func (UnimplementedRvIopServiceServer) FetchRvInteractionsWidget(context.Context, *GetRvInteractionsWidgetRequest) (*GetRvInteractionsWidgetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRvInteractionsWidget not implemented")
}
func (UnimplementedRvIopServiceServer) GetComponents(context.Context, *emptypb.Empty) (*GetComponentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComponents not implemented")
}
func (UnimplementedRvIopServiceServer) mustEmbedUnimplementedRvIopServiceServer() {}

// UnsafeRvIopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RvIopServiceServer will
// result in compilation errors.
type UnsafeRvIopServiceServer interface {
	mustEmbedUnimplementedRvIopServiceServer()
}

func RegisterRvIopServiceServer(s grpc.ServiceRegistrar, srv RvIopServiceServer) {
	s.RegisterService(&RvIopService_ServiceDesc, srv)
}

func _RvIopService_FetchRvSubstituteExploitFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRvSubstituteOrganicFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvIopServiceServer).FetchRvSubstituteExploitFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvIopService_FetchRvSubstituteExploitFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvIopServiceServer).FetchRvSubstituteExploitFeed(ctx, req.(*GetRvSubstituteOrganicFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RvIopService_FetchRvSubstituteExploreFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRvSubstituteCtFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvIopServiceServer).FetchRvSubstituteExploreFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvIopService_FetchRvSubstituteExploreFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvIopServiceServer).FetchRvSubstituteExploreFeed(ctx, req.(*GetRvSubstituteCtFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RvIopService_FetchRvSubstituteAdFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRvSubstituteAdFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvIopServiceServer).FetchRvSubstituteAdFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvIopService_FetchRvSubstituteAdFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvIopServiceServer).FetchRvSubstituteAdFeed(ctx, req.(*GetRvSubstituteAdFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RvIopService_FetchCrossSellWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCrossSellWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvIopServiceServer).FetchCrossSellWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvIopService_FetchCrossSellWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvIopServiceServer).FetchCrossSellWidget(ctx, req.(*GetCrossSellWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RvIopService_FetchCrossSellFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCrossSellFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvIopServiceServer).FetchCrossSellFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvIopService_FetchCrossSellFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvIopServiceServer).FetchCrossSellFeed(ctx, req.(*GetCrossSellFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RvIopService_FetchRvInteractionsFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRvInteractionsFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvIopServiceServer).FetchRvInteractionsFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvIopService_FetchRvInteractionsFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvIopServiceServer).FetchRvInteractionsFeed(ctx, req.(*GetRvInteractionsFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RvIopService_FetchRvInteractionsWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRvInteractionsWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvIopServiceServer).FetchRvInteractionsWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvIopService_FetchRvInteractionsWidget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvIopServiceServer).FetchRvInteractionsWidget(ctx, req.(*GetRvInteractionsWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RvIopService_GetComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvIopServiceServer).GetComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvIopService_GetComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvIopServiceServer).GetComponents(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RvIopService_ServiceDesc is the grpc.ServiceDesc for RvIopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RvIopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rviop.RvIopService",
	HandlerType: (*RvIopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchRvSubstituteExploitFeed",
			Handler:    _RvIopService_FetchRvSubstituteExploitFeed_Handler,
		},
		{
			MethodName: "FetchRvSubstituteExploreFeed",
			Handler:    _RvIopService_FetchRvSubstituteExploreFeed_Handler,
		},
		{
			MethodName: "FetchRvSubstituteAdFeed",
			Handler:    _RvIopService_FetchRvSubstituteAdFeed_Handler,
		},
		{
			MethodName: "FetchCrossSellWidget",
			Handler:    _RvIopService_FetchCrossSellWidget_Handler,
		},
		{
			MethodName: "FetchCrossSellFeed",
			Handler:    _RvIopService_FetchCrossSellFeed_Handler,
		},
		{
			MethodName: "FetchRvInteractionsFeed",
			Handler:    _RvIopService_FetchRvInteractionsFeed_Handler,
		},
		{
			MethodName: "FetchRvInteractionsWidget",
			Handler:    _RvIopService_FetchRvInteractionsWidget_Handler,
		},
		{
			MethodName: "GetComponents",
			Handler:    _RvIopService_GetComponents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rv-iop/api.proto",
}
