// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.32.0
// source: feedaggregator/rv/api.proto

package rv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RvFeedHandler_FetchRvFeed_FullMethodName             = "/rvfeedaggregator.RvFeedHandler/FetchRvFeed"
	RvFeedHandler_FetchRvInteractionsFeed_FullMethodName = "/rvfeedaggregator.RvFeedHandler/FetchRvInteractionsFeed"
)

// RvFeedHandlerClient is the client API for RvFeedHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RvFeedHandlerClient interface {
	FetchRvFeed(ctx context.Context, in *RecentlyViewedRequest, opts ...grpc.CallOption) (*RecentlyViewedResponse, error)
	FetchRvInteractionsFeed(ctx context.Context, in *RvInteractionsFeedRequest, opts ...grpc.CallOption) (*RvInteractionsFeedResponse, error)
}

type rvFeedHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewRvFeedHandlerClient(cc grpc.ClientConnInterface) RvFeedHandlerClient {
	return &rvFeedHandlerClient{cc}
}

func (c *rvFeedHandlerClient) FetchRvFeed(ctx context.Context, in *RecentlyViewedRequest, opts ...grpc.CallOption) (*RecentlyViewedResponse, error) {
	out := new(RecentlyViewedResponse)
	err := c.cc.Invoke(ctx, RvFeedHandler_FetchRvFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rvFeedHandlerClient) FetchRvInteractionsFeed(ctx context.Context, in *RvInteractionsFeedRequest, opts ...grpc.CallOption) (*RvInteractionsFeedResponse, error) {
	out := new(RvInteractionsFeedResponse)
	err := c.cc.Invoke(ctx, RvFeedHandler_FetchRvInteractionsFeed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RvFeedHandlerServer is the server API for RvFeedHandler service.
// All implementations must embed UnimplementedRvFeedHandlerServer
// for forward compatibility
type RvFeedHandlerServer interface {
	FetchRvFeed(context.Context, *RecentlyViewedRequest) (*RecentlyViewedResponse, error)
	FetchRvInteractionsFeed(context.Context, *RvInteractionsFeedRequest) (*RvInteractionsFeedResponse, error)
	mustEmbedUnimplementedRvFeedHandlerServer()
}

// UnimplementedRvFeedHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedRvFeedHandlerServer struct {
}

func (UnimplementedRvFeedHandlerServer) FetchRvFeed(context.Context, *RecentlyViewedRequest) (*RecentlyViewedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRvFeed not implemented")
}
func (UnimplementedRvFeedHandlerServer) FetchRvInteractionsFeed(context.Context, *RvInteractionsFeedRequest) (*RvInteractionsFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchRvInteractionsFeed not implemented")
}
func (UnimplementedRvFeedHandlerServer) mustEmbedUnimplementedRvFeedHandlerServer() {}

// UnsafeRvFeedHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RvFeedHandlerServer will
// result in compilation errors.
type UnsafeRvFeedHandlerServer interface {
	mustEmbedUnimplementedRvFeedHandlerServer()
}

func RegisterRvFeedHandlerServer(s grpc.ServiceRegistrar, srv RvFeedHandlerServer) {
	s.RegisterService(&RvFeedHandler_ServiceDesc, srv)
}

func _RvFeedHandler_FetchRvFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentlyViewedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvFeedHandlerServer).FetchRvFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvFeedHandler_FetchRvFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvFeedHandlerServer).FetchRvFeed(ctx, req.(*RecentlyViewedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RvFeedHandler_FetchRvInteractionsFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RvInteractionsFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RvFeedHandlerServer).FetchRvInteractionsFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RvFeedHandler_FetchRvInteractionsFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RvFeedHandlerServer).FetchRvInteractionsFeed(ctx, req.(*RvInteractionsFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RvFeedHandler_ServiceDesc is the grpc.ServiceDesc for RvFeedHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RvFeedHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rvfeedaggregator.RvFeedHandler",
	HandlerType: (*RvFeedHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchRvFeed",
			Handler:    _RvFeedHandler_FetchRvFeed_Handler,
		},
		{
			MethodName: "FetchRvInteractionsFeed",
			Handler:    _RvFeedHandler_FetchRvInteractionsFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedaggregator/rv/api.proto",
}
