// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pdp/v2/api.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pdp_v2_api_proto protoreflect.FileDescriptor

const file_pdp_v2_api_proto_rawDesc = "" +
	"\n" +
	"\x10pdp/v2/api.proto\x12\x14pdpfeedaggregator.v2\x1a\x14pdp/v2/request.proto\x1a\x15pdp/v2/response.proto2|\n" +
	"\x10PdpFeedHandlerV2\x12h\n" +
	"\x0eFetchPdpFeedV2\x12+.pdpfeedaggregator.RecommendationsRequestV2\x1a'.pdpfeedaggregator.v2.PdpFeedResponseV2\"\x00B\aZ\x05../v2b\x06proto3"

var file_pdp_v2_api_proto_goTypes = []any{
	(*RecommendationsRequestV2)(nil), // 0: pdpfeedaggregator.RecommendationsRequestV2
	(*PdpFeedResponseV2)(nil),        // 1: pdpfeedaggregator.v2.PdpFeedResponseV2
}
var file_pdp_v2_api_proto_depIdxs = []int32{
	0, // 0: pdpfeedaggregator.v2.PdpFeedHandlerV2.FetchPdpFeedV2:input_type -> pdpfeedaggregator.RecommendationsRequestV2
	1, // 1: pdpfeedaggregator.v2.PdpFeedHandlerV2.FetchPdpFeedV2:output_type -> pdpfeedaggregator.v2.PdpFeedResponseV2
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pdp_v2_api_proto_init() }
func file_pdp_v2_api_proto_init() {
	if File_pdp_v2_api_proto != nil {
		return
	}
	file_pdp_v2_request_proto_init()
	file_pdp_v2_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pdp_v2_api_proto_rawDesc), len(file_pdp_v2_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pdp_v2_api_proto_goTypes,
		DependencyIndexes: file_pdp_v2_api_proto_depIdxs,
	}.Build()
	File_pdp_v2_api_proto = out.File
	file_pdp_v2_api_proto_goTypes = nil
	file_pdp_v2_api_proto_depIdxs = nil
}
