// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pdp/v2/api.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PdpFeedHandlerV2_FetchPdpFeedV2_FullMethodName = "/pdpfeedaggregator.v2.PdpFeedHandlerV2/FetchPdpFeedV2"
)

// PdpFeedHandlerV2Client is the client API for PdpFeedHandlerV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdpFeedHandlerV2Client interface {
	FetchPdpFeedV2(ctx context.Context, in *RecommendationsRequestV2, opts ...grpc.CallOption) (*PdpFeedResponseV2, error)
}

type pdpFeedHandlerV2Client struct {
	cc grpc.ClientConnInterface
}

func NewPdpFeedHandlerV2Client(cc grpc.ClientConnInterface) PdpFeedHandlerV2Client {
	return &pdpFeedHandlerV2Client{cc}
}

func (c *pdpFeedHandlerV2Client) FetchPdpFeedV2(ctx context.Context, in *RecommendationsRequestV2, opts ...grpc.CallOption) (*PdpFeedResponseV2, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PdpFeedResponseV2)
	err := c.cc.Invoke(ctx, PdpFeedHandlerV2_FetchPdpFeedV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdpFeedHandlerV2Server is the server API for PdpFeedHandlerV2 service.
// All implementations must embed UnimplementedPdpFeedHandlerV2Server
// for forward compatibility.
type PdpFeedHandlerV2Server interface {
	FetchPdpFeedV2(context.Context, *RecommendationsRequestV2) (*PdpFeedResponseV2, error)
	mustEmbedUnimplementedPdpFeedHandlerV2Server()
}

// UnimplementedPdpFeedHandlerV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPdpFeedHandlerV2Server struct{}

func (UnimplementedPdpFeedHandlerV2Server) FetchPdpFeedV2(context.Context, *RecommendationsRequestV2) (*PdpFeedResponseV2, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchPdpFeedV2 not implemented")
}
func (UnimplementedPdpFeedHandlerV2Server) mustEmbedUnimplementedPdpFeedHandlerV2Server() {}
func (UnimplementedPdpFeedHandlerV2Server) testEmbeddedByValue()                          {}

// UnsafePdpFeedHandlerV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdpFeedHandlerV2Server will
// result in compilation errors.
type UnsafePdpFeedHandlerV2Server interface {
	mustEmbedUnimplementedPdpFeedHandlerV2Server()
}

func RegisterPdpFeedHandlerV2Server(s grpc.ServiceRegistrar, srv PdpFeedHandlerV2Server) {
	// If the following call pancis, it indicates UnimplementedPdpFeedHandlerV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PdpFeedHandlerV2_ServiceDesc, srv)
}

func _PdpFeedHandlerV2_FetchPdpFeedV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationsRequestV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdpFeedHandlerV2Server).FetchPdpFeedV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PdpFeedHandlerV2_FetchPdpFeedV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdpFeedHandlerV2Server).FetchPdpFeedV2(ctx, req.(*RecommendationsRequestV2))
	}
	return interceptor(ctx, in, info, handler)
}

// PdpFeedHandlerV2_ServiceDesc is the grpc.ServiceDesc for PdpFeedHandlerV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdpFeedHandlerV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdpfeedaggregator.v2.PdpFeedHandlerV2",
	HandlerType: (*PdpFeedHandlerV2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchPdpFeedV2",
			Handler:    _PdpFeedHandlerV2_FetchPdpFeedV2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pdp/v2/api.proto",
}
