// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pdp/v2/request.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendationsRequestV2 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cursor           string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Offset           int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit            int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	FeedType         string                 `protobuf:"bytes,4,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`
	FeedContext      string                 `protobuf:"bytes,5,opt,name=feed_context,json=feedContext,proto3" json:"feed_context,omitempty"`
	CatalogId        int32                  `protobuf:"varint,6,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"` // [required=true]
	ProductId        int32                  `protobuf:"varint,7,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SubSubCategoryId int32                  `protobuf:"varint,8,opt,name=sub_sub_category_id,json=subSubCategoryId,proto3" json:"sub_sub_category_id,omitempty"` // [(validate.rules).int32.gt = 0]
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecommendationsRequestV2) Reset() {
	*x = RecommendationsRequestV2{}
	mi := &file_pdp_v2_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsRequestV2) ProtoMessage() {}

func (x *RecommendationsRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_pdp_v2_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsRequestV2.ProtoReflect.Descriptor instead.
func (*RecommendationsRequestV2) Descriptor() ([]byte, []int) {
	return file_pdp_v2_request_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendationsRequestV2) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *RecommendationsRequestV2) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RecommendationsRequestV2) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecommendationsRequestV2) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

func (x *RecommendationsRequestV2) GetFeedContext() string {
	if x != nil {
		return x.FeedContext
	}
	return ""
}

func (x *RecommendationsRequestV2) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *RecommendationsRequestV2) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *RecommendationsRequestV2) GetSubSubCategoryId() int32 {
	if x != nil {
		return x.SubSubCategoryId
	}
	return 0
}

var File_pdp_v2_request_proto protoreflect.FileDescriptor

const file_pdp_v2_request_proto_rawDesc = "" +
	"\n" +
	"\x14pdp/v2/request.proto\x12\x11pdpfeedaggregator\"\x8d\x02\n" +
	"\x18RecommendationsRequestV2\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tfeed_type\x18\x04 \x01(\tR\bfeedType\x12!\n" +
	"\ffeed_context\x18\x05 \x01(\tR\vfeedContext\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x06 \x01(\x05R\tcatalogId\x12\x1d\n" +
	"\n" +
	"product_id\x18\a \x01(\x05R\tproductId\x12-\n" +
	"\x13sub_sub_category_id\x18\b \x01(\x05R\x10subSubCategoryIdB\aZ\x05../v2b\x06proto3"

var (
	file_pdp_v2_request_proto_rawDescOnce sync.Once
	file_pdp_v2_request_proto_rawDescData []byte
)

func file_pdp_v2_request_proto_rawDescGZIP() []byte {
	file_pdp_v2_request_proto_rawDescOnce.Do(func() {
		file_pdp_v2_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pdp_v2_request_proto_rawDesc), len(file_pdp_v2_request_proto_rawDesc)))
	})
	return file_pdp_v2_request_proto_rawDescData
}

var file_pdp_v2_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pdp_v2_request_proto_goTypes = []any{
	(*RecommendationsRequestV2)(nil), // 0: pdpfeedaggregator.RecommendationsRequestV2
}
var file_pdp_v2_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pdp_v2_request_proto_init() }
func file_pdp_v2_request_proto_init() {
	if File_pdp_v2_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pdp_v2_request_proto_rawDesc), len(file_pdp_v2_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pdp_v2_request_proto_goTypes,
		DependencyIndexes: file_pdp_v2_request_proto_depIdxs,
		MessageInfos:      file_pdp_v2_request_proto_msgTypes,
	}.Build()
	File_pdp_v2_request_proto = out.File
	file_pdp_v2_request_proto_goTypes = nil
	file_pdp_v2_request_proto_depIdxs = nil
}
