// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pdp/v2/response.proto

package v2

import (
	feedcommonresponse "github.com/Meesho/feed-aggregator-go/client/grpc/feedcommonresponse"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PdpFeedResponseV2 struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	FeedResponse  *feedcommonresponse.FeedResponse `protobuf:"bytes,1,opt,name=feed_response,json=feedResponse,proto3" json:"feed_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdpFeedResponseV2) Reset() {
	*x = PdpFeedResponseV2{}
	mi := &file_pdp_v2_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdpFeedResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdpFeedResponseV2) ProtoMessage() {}

func (x *PdpFeedResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_pdp_v2_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdpFeedResponseV2.ProtoReflect.Descriptor instead.
func (*PdpFeedResponseV2) Descriptor() ([]byte, []int) {
	return file_pdp_v2_response_proto_rawDescGZIP(), []int{0}
}

func (x *PdpFeedResponseV2) GetFeedResponse() *feedcommonresponse.FeedResponse {
	if x != nil {
		return x.FeedResponse
	}
	return nil
}

var File_pdp_v2_response_proto protoreflect.FileDescriptor

const file_pdp_v2_response_proto_rawDesc = "" +
	"\n" +
	"\x15pdp/v2/response.proto\x12\x14pdpfeedaggregator.v2\x1a!feedcommonresponse/response.proto\"R\n" +
	"\x11PdpFeedResponseV2\x12=\n" +
	"\rfeed_response\x18\x01 \x01(\v2\x18.feedcommon.FeedResponseR\ffeedResponseB\aZ\x05../v2b\x06proto3"

var (
	file_pdp_v2_response_proto_rawDescOnce sync.Once
	file_pdp_v2_response_proto_rawDescData []byte
)

func file_pdp_v2_response_proto_rawDescGZIP() []byte {
	file_pdp_v2_response_proto_rawDescOnce.Do(func() {
		file_pdp_v2_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pdp_v2_response_proto_rawDesc), len(file_pdp_v2_response_proto_rawDesc)))
	})
	return file_pdp_v2_response_proto_rawDescData
}

var file_pdp_v2_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pdp_v2_response_proto_goTypes = []any{
	(*PdpFeedResponseV2)(nil),               // 0: pdpfeedaggregator.v2.PdpFeedResponseV2
	(*feedcommonresponse.FeedResponse)(nil), // 1: feedcommon.FeedResponse
}
var file_pdp_v2_response_proto_depIdxs = []int32{
	1, // 0: pdpfeedaggregator.v2.PdpFeedResponseV2.feed_response:type_name -> feedcommon.FeedResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pdp_v2_response_proto_init() }
func file_pdp_v2_response_proto_init() {
	if File_pdp_v2_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pdp_v2_response_proto_rawDesc), len(file_pdp_v2_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pdp_v2_response_proto_goTypes,
		DependencyIndexes: file_pdp_v2_response_proto_depIdxs,
		MessageInfos:      file_pdp_v2_response_proto_msgTypes,
	}.Build()
	File_pdp_v2_response_proto = out.File
	file_pdp_v2_response_proto_goTypes = nil
	file_pdp_v2_response_proto_depIdxs = nil
}
