// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: feedaggregator/foryou/api.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeedHandler_FetchForYouFeed_FullMethodName = "/FeedHandler/FetchForYouFeed"
)

// FeedHandlerClient is the client API for FeedHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedHandlerClient interface {
	FetchForYouFeed(ctx context.Context, in *ForYouFeedRequest, opts ...grpc.CallOption) (*ForYouFeedResponse, error)
}

type feedHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedHandlerClient(cc grpc.ClientConnInterface) FeedHandlerClient {
	return &feedHandlerClient{cc}
}

func (c *feedHandlerClient) FetchForYouFeed(ctx context.Context, in *ForYouFeedRequest, opts ...grpc.CallOption) (*ForYouFeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForYouFeedResponse)
	err := c.cc.Invoke(ctx, FeedHandler_FetchForYouFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedHandlerServer is the server API for FeedHandler service.
// All implementations must embed UnimplementedFeedHandlerServer
// for forward compatibility.
type FeedHandlerServer interface {
	FetchForYouFeed(context.Context, *ForYouFeedRequest) (*ForYouFeedResponse, error)
	mustEmbedUnimplementedFeedHandlerServer()
}

// UnimplementedFeedHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedHandlerServer struct{}

func (UnimplementedFeedHandlerServer) FetchForYouFeed(context.Context, *ForYouFeedRequest) (*ForYouFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchForYouFeed not implemented")
}
func (UnimplementedFeedHandlerServer) mustEmbedUnimplementedFeedHandlerServer() {}
func (UnimplementedFeedHandlerServer) testEmbeddedByValue()                     {}

// UnsafeFeedHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedHandlerServer will
// result in compilation errors.
type UnsafeFeedHandlerServer interface {
	mustEmbedUnimplementedFeedHandlerServer()
}

func RegisterFeedHandlerServer(s grpc.ServiceRegistrar, srv FeedHandlerServer) {
	// If the following call pancis, it indicates UnimplementedFeedHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedHandler_ServiceDesc, srv)
}

func _FeedHandler_FetchForYouFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForYouFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedHandlerServer).FetchForYouFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedHandler_FetchForYouFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedHandlerServer).FetchForYouFeed(ctx, req.(*ForYouFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedHandler_ServiceDesc is the grpc.ServiceDesc for FeedHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FeedHandler",
	HandlerType: (*FeedHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchForYouFeed",
			Handler:    _FeedHandler_FetchForYouFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedaggregator/foryou/api.proto",
}