// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: feedaggregator/crosssell/api.proto

package crosssell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_feedaggregator_crosssell_api_proto protoreflect.FileDescriptor

const file_feedaggregator_crosssell_api_proto_rawDesc = "" +
	"\n" +
	"\"feedaggregator/crosssell/api.proto\x12\x03api\x1a&feedaggregator/crosssell/request.proto\x1a'feedaggregator/crosssell/response.proto2`\n" +
	"\x10CrossSellHandler\x12L\n" +
	"\x12FetchCrossSellFeed\x12\x19.request.CrossSellRequest\x1a\x1b.response.CrossSellResponseB\x0eZ\f../crosssellb\x06proto3"

var file_feedaggregator_crosssell_api_proto_goTypes = []any{
	(*CrossSellRequest)(nil),  // 0: request.CrossSellRequest
	(*CrossSellResponse)(nil), // 1: response.CrossSellResponse
}
var file_feedaggregator_crosssell_api_proto_depIdxs = []int32{
	0, // 0: api.CrossSellHandler.FetchCrossSellFeed:input_type -> request.CrossSellRequest
	1, // 1: api.CrossSellHandler.FetchCrossSellFeed:output_type -> response.CrossSellResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feedaggregator_crosssell_api_proto_init() }
func file_feedaggregator_crosssell_api_proto_init() {
	if File_feedaggregator_crosssell_api_proto != nil {
		return
	}
	file_feedaggregator_crosssell_request_proto_init()
	file_feedaggregator_crosssell_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedaggregator_crosssell_api_proto_rawDesc), len(file_feedaggregator_crosssell_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedaggregator_crosssell_api_proto_goTypes,
		DependencyIndexes: file_feedaggregator_crosssell_api_proto_depIdxs,
	}.Build()
	File_feedaggregator_crosssell_api_proto = out.File
	file_feedaggregator_crosssell_api_proto_goTypes = nil
	file_feedaggregator_crosssell_api_proto_depIdxs = nil
}
