// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: feedaggregator/crosssell/api.proto

package crosssell

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CrossSellHandler_FetchCrossSellFeed_FullMethodName = "/api.CrossSellHandler/FetchCrossSellFeed"
)

// CrossSellHandlerClient is the client API for CrossSellHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrossSellHandlerClient interface {
	FetchCrossSellFeed(ctx context.Context, in *CrossSellRequest, opts ...grpc.CallOption) (*CrossSellResponse, error)
}

type crossSellHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewCrossSellHandlerClient(cc grpc.ClientConnInterface) CrossSellHandlerClient {
	return &crossSellHandlerClient{cc}
}

func (c *crossSellHandlerClient) FetchCrossSellFeed(ctx context.Context, in *CrossSellRequest, opts ...grpc.CallOption) (*CrossSellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrossSellResponse)
	err := c.cc.Invoke(ctx, CrossSellHandler_FetchCrossSellFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrossSellHandlerServer is the server API for CrossSellHandler service.
// All implementations must embed UnimplementedCrossSellHandlerServer
// for forward compatibility.
type CrossSellHandlerServer interface {
	FetchCrossSellFeed(context.Context, *CrossSellRequest) (*CrossSellResponse, error)
	mustEmbedUnimplementedCrossSellHandlerServer()
}

// UnimplementedCrossSellHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrossSellHandlerServer struct{}

func (UnimplementedCrossSellHandlerServer) FetchCrossSellFeed(context.Context, *CrossSellRequest) (*CrossSellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCrossSellFeed not implemented")
}
func (UnimplementedCrossSellHandlerServer) mustEmbedUnimplementedCrossSellHandlerServer() {}
func (UnimplementedCrossSellHandlerServer) testEmbeddedByValue()                          {}

// UnsafeCrossSellHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrossSellHandlerServer will
// result in compilation errors.
type UnsafeCrossSellHandlerServer interface {
	mustEmbedUnimplementedCrossSellHandlerServer()
}

func RegisterCrossSellHandlerServer(s grpc.ServiceRegistrar, srv CrossSellHandlerServer) {
	// If the following call pancis, it indicates UnimplementedCrossSellHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrossSellHandler_ServiceDesc, srv)
}

func _CrossSellHandler_FetchCrossSellFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossSellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrossSellHandlerServer).FetchCrossSellFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrossSellHandler_FetchCrossSellFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrossSellHandlerServer).FetchCrossSellFeed(ctx, req.(*CrossSellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrossSellHandler_ServiceDesc is the grpc.ServiceDesc for CrossSellHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrossSellHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.CrossSellHandler",
	HandlerType: (*CrossSellHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchCrossSellFeed",
			Handler:    _CrossSellHandler_FetchCrossSellFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedaggregator/crosssell/api.proto",
}
