// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: feedaggregator/crosssell/request.proto

package crosssell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClickContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SscatId       int32                  `protobuf:"varint,2,opt,name=sscat_id,json=sscatId,proto3" json:"sscat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickContext) Reset() {
	*x = ClickContext{}
	mi := &file_feedaggregator_crosssell_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickContext) ProtoMessage() {}

func (x *ClickContext) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_crosssell_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickContext.ProtoReflect.Descriptor instead.
func (*ClickContext) Descriptor() ([]byte, []int) {
	return file_feedaggregator_crosssell_request_proto_rawDescGZIP(), []int{0}
}

func (x *ClickContext) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ClickContext) GetSscatId() int32 {
	if x != nil {
		return x.SscatId
	}
	return 0
}

type CrossSellRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor                string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Screen                string                 `protobuf:"bytes,3,opt,name=screen,proto3" json:"screen,omitempty"`
	Limit                 int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	WidgetParentProductId int32                  `protobuf:"varint,5,opt,name=widget_parent_product_id,json=widgetParentProductId,proto3" json:"widget_parent_product_id,omitempty"`
	ClickContext          *ClickContext          `protobuf:"bytes,6,opt,name=click_context,json=clickContext,proto3" json:"click_context,omitempty"`
	Tenant                string                 `protobuf:"bytes,7,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CrossSellRequest) Reset() {
	*x = CrossSellRequest{}
	mi := &file_feedaggregator_crosssell_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossSellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossSellRequest) ProtoMessage() {}

func (x *CrossSellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_crosssell_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossSellRequest.ProtoReflect.Descriptor instead.
func (*CrossSellRequest) Descriptor() ([]byte, []int) {
	return file_feedaggregator_crosssell_request_proto_rawDescGZIP(), []int{1}
}

func (x *CrossSellRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CrossSellRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *CrossSellRequest) GetScreen() string {
	if x != nil {
		return x.Screen
	}
	return ""
}

func (x *CrossSellRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CrossSellRequest) GetWidgetParentProductId() int32 {
	if x != nil {
		return x.WidgetParentProductId
	}
	return 0
}

func (x *CrossSellRequest) GetClickContext() *ClickContext {
	if x != nil {
		return x.ClickContext
	}
	return nil
}

func (x *CrossSellRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

var File_feedaggregator_crosssell_request_proto protoreflect.FileDescriptor

const file_feedaggregator_crosssell_request_proto_rawDesc = "" +
	"\n" +
	"&feedaggregator/crosssell/request.proto\x12\arequest\"H\n" +
	"\fClickContext\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x19\n" +
	"\bsscat_id\x18\x02 \x01(\x05R\asscatId\"\xfe\x01\n" +
	"\x10CrossSellRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x16\n" +
	"\x06screen\x18\x03 \x01(\tR\x06screen\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x127\n" +
	"\x18widget_parent_product_id\x18\x05 \x01(\x05R\x15widgetParentProductId\x12:\n" +
	"\rclick_context\x18\x06 \x01(\v2\x15.request.ClickContextR\fclickContext\x12\x16\n" +
	"\x06tenant\x18\a \x01(\tR\x06tenantB\x0eZ\f../crosssellb\x06proto3"

var (
	file_feedaggregator_crosssell_request_proto_rawDescOnce sync.Once
	file_feedaggregator_crosssell_request_proto_rawDescData []byte
)

func file_feedaggregator_crosssell_request_proto_rawDescGZIP() []byte {
	file_feedaggregator_crosssell_request_proto_rawDescOnce.Do(func() {
		file_feedaggregator_crosssell_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedaggregator_crosssell_request_proto_rawDesc), len(file_feedaggregator_crosssell_request_proto_rawDesc)))
	})
	return file_feedaggregator_crosssell_request_proto_rawDescData
}

var file_feedaggregator_crosssell_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_feedaggregator_crosssell_request_proto_goTypes = []any{
	(*ClickContext)(nil),     // 0: request.ClickContext
	(*CrossSellRequest)(nil), // 1: request.CrossSellRequest
}
var file_feedaggregator_crosssell_request_proto_depIdxs = []int32{
	0, // 0: request.CrossSellRequest.click_context:type_name -> request.ClickContext
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feedaggregator_crosssell_request_proto_init() }
func file_feedaggregator_crosssell_request_proto_init() {
	if File_feedaggregator_crosssell_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedaggregator_crosssell_request_proto_rawDesc), len(file_feedaggregator_crosssell_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedaggregator_crosssell_request_proto_goTypes,
		DependencyIndexes: file_feedaggregator_crosssell_request_proto_depIdxs,
		MessageInfos:      file_feedaggregator_crosssell_request_proto_msgTypes,
	}.Build()
	File_feedaggregator_crosssell_request_proto = out.File
	file_feedaggregator_crosssell_request_proto_goTypes = nil
	file_feedaggregator_crosssell_request_proto_depIdxs = nil
}
