// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: feedaggregator/crosssell/response.proto

package crosssell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CatalogId     int32                  `protobuf:"varint,2,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentMetadata) Reset() {
	*x = ParentMetadata{}
	mi := &file_feedaggregator_crosssell_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentMetadata) ProtoMessage() {}

func (x *ParentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_crosssell_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentMetadata.ProtoReflect.Descriptor instead.
func (*ParentMetadata) Descriptor() ([]byte, []int) {
	return file_feedaggregator_crosssell_response_proto_rawDescGZIP(), []int{0}
}

func (x *ParentMetadata) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ParentMetadata) GetCatalogId() int32 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

type TrackingMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedSource    string                 `protobuf:"bytes,1,opt,name=feed_source,json=feedSource,proto3" json:"feed_source,omitempty"`
	TrackingId    string                 `protobuf:"bytes,2,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingMetadata) Reset() {
	*x = TrackingMetadata{}
	mi := &file_feedaggregator_crosssell_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingMetadata) ProtoMessage() {}

func (x *TrackingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_crosssell_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingMetadata.ProtoReflect.Descriptor instead.
func (*TrackingMetadata) Descriptor() ([]byte, []int) {
	return file_feedaggregator_crosssell_response_proto_rawDescGZIP(), []int{1}
}

func (x *TrackingMetadata) GetFeedSource() string {
	if x != nil {
		return x.FeedSource
	}
	return ""
}

func (x *TrackingMetadata) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type CrossSellResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Entities       []int32                `protobuf:"varint,1,rep,packed,name=entities,proto3" json:"entities,omitempty"`
	EntityType     string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	ParentMetadata *ParentMetadata        `protobuf:"bytes,3,opt,name=parent_metadata,json=parentMetadata,proto3" json:"parent_metadata,omitempty"`
	Cursor         string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Tracking       *TrackingMetadata      `protobuf:"bytes,5,opt,name=tracking,proto3" json:"tracking,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CrossSellResponse) Reset() {
	*x = CrossSellResponse{}
	mi := &file_feedaggregator_crosssell_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossSellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossSellResponse) ProtoMessage() {}

func (x *CrossSellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedaggregator_crosssell_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossSellResponse.ProtoReflect.Descriptor instead.
func (*CrossSellResponse) Descriptor() ([]byte, []int) {
	return file_feedaggregator_crosssell_response_proto_rawDescGZIP(), []int{2}
}

func (x *CrossSellResponse) GetEntities() []int32 {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *CrossSellResponse) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *CrossSellResponse) GetParentMetadata() *ParentMetadata {
	if x != nil {
		return x.ParentMetadata
	}
	return nil
}

func (x *CrossSellResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *CrossSellResponse) GetTracking() *TrackingMetadata {
	if x != nil {
		return x.Tracking
	}
	return nil
}

var File_feedaggregator_crosssell_response_proto protoreflect.FileDescriptor

const file_feedaggregator_crosssell_response_proto_rawDesc = "" +
	"\n" +
	"'feedaggregator/crosssell/response.proto\x12\bresponse\"N\n" +
	"\x0eParentMetadata\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1d\n" +
	"\n" +
	"catalog_id\x18\x02 \x01(\x05R\tcatalogId\"T\n" +
	"\x10TrackingMetadata\x12\x1f\n" +
	"\vfeed_source\x18\x01 \x01(\tR\n" +
	"feedSource\x12\x1f\n" +
	"\vtracking_id\x18\x02 \x01(\tR\n" +
	"trackingId\"\xe3\x01\n" +
	"\x11CrossSellResponse\x12\x1a\n" +
	"\bentities\x18\x01 \x03(\x05R\bentities\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12A\n" +
	"\x0fparent_metadata\x18\x03 \x01(\v2\x18.response.ParentMetadataR\x0eparentMetadata\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x126\n" +
	"\btracking\x18\x05 \x01(\v2\x1a.response.TrackingMetadataR\btrackingB\x0eZ\f../crosssellb\x06proto3"

var (
	file_feedaggregator_crosssell_response_proto_rawDescOnce sync.Once
	file_feedaggregator_crosssell_response_proto_rawDescData []byte
)

func file_feedaggregator_crosssell_response_proto_rawDescGZIP() []byte {
	file_feedaggregator_crosssell_response_proto_rawDescOnce.Do(func() {
		file_feedaggregator_crosssell_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedaggregator_crosssell_response_proto_rawDesc), len(file_feedaggregator_crosssell_response_proto_rawDesc)))
	})
	return file_feedaggregator_crosssell_response_proto_rawDescData
}

var file_feedaggregator_crosssell_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_feedaggregator_crosssell_response_proto_goTypes = []any{
	(*ParentMetadata)(nil),    // 0: response.ParentMetadata
	(*TrackingMetadata)(nil),  // 1: response.TrackingMetadata
	(*CrossSellResponse)(nil), // 2: response.CrossSellResponse
}
var file_feedaggregator_crosssell_response_proto_depIdxs = []int32{
	0, // 0: response.CrossSellResponse.parent_metadata:type_name -> response.ParentMetadata
	1, // 1: response.CrossSellResponse.tracking:type_name -> response.TrackingMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_feedaggregator_crosssell_response_proto_init() }
func file_feedaggregator_crosssell_response_proto_init() {
	if File_feedaggregator_crosssell_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedaggregator_crosssell_response_proto_rawDesc), len(file_feedaggregator_crosssell_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedaggregator_crosssell_response_proto_goTypes,
		DependencyIndexes: file_feedaggregator_crosssell_response_proto_depIdxs,
		MessageInfos:      file_feedaggregator_crosssell_response_proto_msgTypes,
	}.Build()
	File_feedaggregator_crosssell_response_proto = out.File
	file_feedaggregator_crosssell_response_proto_goTypes = nil
	file_feedaggregator_crosssell_response_proto_depIdxs = nil
}
