// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: feedcommonresponse/response.proto

package feedcommonresponse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_feedcommonresponse_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_feedcommonresponse_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_feedcommonresponse_response_proto_rawDescGZIP(), []int{0}
}

func (x *MetaData) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type FeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Metadata      *MetaData              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedResponse) Reset() {
	*x = FeedResponse{}
	mi := &file_feedcommonresponse_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedResponse) ProtoMessage() {}

func (x *FeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedcommonresponse_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedResponse.ProtoReflect.Descriptor instead.
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return file_feedcommonresponse_response_proto_rawDescGZIP(), []int{1}
}

func (x *FeedResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *FeedResponse) GetMetadata() *MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Entity:
	//
	//	*Entity_CatalogView
	//	*Entity_ReelView
	Entity        isEntity_Entity `protobuf_oneof:"entity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_feedcommonresponse_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_feedcommonresponse_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_feedcommonresponse_response_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetEntity() isEntity_Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *Entity) GetCatalogView() *CatalogView {
	if x != nil {
		if x, ok := x.Entity.(*Entity_CatalogView); ok {
			return x.CatalogView
		}
	}
	return nil
}

func (x *Entity) GetReelView() *ReelViewSchema {
	if x != nil {
		if x, ok := x.Entity.(*Entity_ReelView); ok {
			return x.ReelView
		}
	}
	return nil
}

type isEntity_Entity interface {
	isEntity_Entity()
}

type Entity_CatalogView struct {
	CatalogView *CatalogView `protobuf:"bytes,1,opt,name=catalog_view,json=catalogView,proto3,oneof"`
}

type Entity_ReelView struct {
	ReelView *ReelViewSchema `protobuf:"bytes,2,opt,name=reel_view,json=reelView,proto3,oneof"`
}

func (*Entity_CatalogView) isEntity_Entity() {}

func (*Entity_ReelView) isEntity_Entity() {}

type ReelViewSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatalogView   *CatalogView           `protobuf:"bytes,1,opt,name=catalog_view,json=catalogView,proto3" json:"catalog_view,omitempty"` // composition
	ReelData      *ReelData              `protobuf:"bytes,2,opt,name=reel_data,json=reelData,proto3" json:"reel_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReelViewSchema) Reset() {
	*x = ReelViewSchema{}
	mi := &file_feedcommonresponse_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReelViewSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReelViewSchema) ProtoMessage() {}

func (x *ReelViewSchema) ProtoReflect() protoreflect.Message {
	mi := &file_feedcommonresponse_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReelViewSchema.ProtoReflect.Descriptor instead.
func (*ReelViewSchema) Descriptor() ([]byte, []int) {
	return file_feedcommonresponse_response_proto_rawDescGZIP(), []int{3}
}

func (x *ReelViewSchema) GetCatalogView() *CatalogView {
	if x != nil {
		return x.CatalogView
	}
	return nil
}

func (x *ReelViewSchema) GetReelData() *ReelData {
	if x != nil {
		return x.ReelData
	}
	return nil
}

// Minimal ReelData schema for PDP v2. Mirrors older PDP/FY schemas where relevant.
type ReelData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tracker         *Tracker               `protobuf:"bytes,2,opt,name=tracker,proto3" json:"tracker,omitempty"`
	Video           *Video                 `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	HeroCatalog     *CatalogInfo           `protobuf:"bytes,4,opt,name=hero_catalog,json=heroCatalog,proto3" json:"hero_catalog,omitempty"`
	CatalogInfo     []*CatalogInfo         `protobuf:"bytes,5,rep,name=catalog_info,json=catalogInfo,proto3" json:"catalog_info,omitempty"`
	UserName        string                 `protobuf:"bytes,6,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Category        string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	FeedType        string                 `protobuf:"bytes,8,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`
	LikeCount       int32                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,10,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	Gif             string                 `protobuf:"bytes,11,opt,name=gif,proto3" json:"gif,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReelData) Reset() {
	*x = ReelData{}
	mi := &file_feedcommonresponse_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReelData) ProtoMessage() {}

func (x *ReelData) ProtoReflect() protoreflect.Message {
	mi := &file_feedcommonresponse_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReelData.ProtoReflect.Descriptor instead.
func (*ReelData) Descriptor() ([]byte, []int) {
	return file_feedcommonresponse_response_proto_rawDescGZIP(), []int{4}
}

func (x *ReelData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReelData) GetTracker() *Tracker {
	if x != nil {
		return x.Tracker
	}
	return nil
}

func (x *ReelData) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *ReelData) GetHeroCatalog() *CatalogInfo {
	if x != nil {
		return x.HeroCatalog
	}
	return nil
}

func (x *ReelData) GetCatalogInfo() []*CatalogInfo {
	if x != nil {
		return x.CatalogInfo
	}
	return nil
}

func (x *ReelData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ReelData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ReelData) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

func (x *ReelData) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ReelData) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *ReelData) GetGif() string {
	if x != nil {
		return x.Gif
	}
	return ""
}

type Tracker struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrackerId       string                 `protobuf:"bytes,1,opt,name=tracker_id,json=trackerId,proto3" json:"tracker_id,omitempty"`
	IsProductResult bool                   `protobuf:"varint,2,opt,name=is_product_result,json=isProductResult,proto3" json:"is_product_result,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Tracker) Reset() {
	*x = Tracker{}
	mi := &file_feedcommonresponse_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tracker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tracker) ProtoMessage() {}

func (x *Tracker) ProtoReflect() protoreflect.Message {
	mi := &file_feedcommonresponse_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tracker.ProtoReflect.Descriptor instead.
func (*Tracker) Descriptor() ([]byte, []int) {
	return file_feedcommonresponse_response_proto_rawDescGZIP(), []int{5}
}

func (x *Tracker) GetTrackerId() string {
	if x != nil {
		return x.TrackerId
	}
	return ""
}

func (x *Tracker) GetIsProductResult() bool {
	if x != nil {
		return x.IsProductResult
	}
	return false
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ThumbNailWebp string                 `protobuf:"bytes,2,opt,name=thumb_nail_webp,json=thumbNailWebp,proto3" json:"thumb_nail_webp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_feedcommonresponse_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_feedcommonresponse_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_feedcommonresponse_response_proto_rawDescGZIP(), []int{6}
}

func (x *Video) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Video) GetThumbNailWebp() string {
	if x != nil {
		return x.ThumbNailWebp
	}
	return ""
}

type CatalogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HeroPid       int32                  `protobuf:"varint,2,opt,name=hero_pid,json=heroPid,proto3" json:"hero_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogInfo) Reset() {
	*x = CatalogInfo{}
	mi := &file_feedcommonresponse_response_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogInfo) ProtoMessage() {}

func (x *CatalogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_feedcommonresponse_response_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogInfo.ProtoReflect.Descriptor instead.
func (*CatalogInfo) Descriptor() ([]byte, []int) {
	return file_feedcommonresponse_response_proto_rawDescGZIP(), []int{7}
}

func (x *CatalogInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CatalogInfo) GetHeroPid() int32 {
	if x != nil {
		return x.HeroPid
	}
	return 0
}

var File_feedcommonresponse_response_proto protoreflect.FileDescriptor

const file_feedcommonresponse_response_proto_rawDesc = "" +
	"\n" +
	"!feedcommonresponse/response.proto\x12\n" +
	"feedcommon\x1a*feedcommonresponse/CatalogViewSchema.proto\"\"\n" +
	"\bMetaData\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"p\n" +
	"\fFeedResponse\x12.\n" +
	"\bentities\x18\x01 \x03(\v2\x12.feedcommon.EntityR\bentities\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.feedcommon.MetaDataR\bmetadata\"\x80\x01\n" +
	"\x06Entity\x121\n" +
	"\fcatalog_view\x18\x01 \x01(\v2\f.CatalogViewH\x00R\vcatalogView\x129\n" +
	"\treel_view\x18\x02 \x01(\v2\x1a.feedcommon.ReelViewSchemaH\x00R\breelViewB\b\n" +
	"\x06entity\"t\n" +
	"\x0eReelViewSchema\x12/\n" +
	"\fcatalog_view\x18\x01 \x01(\v2\f.CatalogViewR\vcatalogView\x121\n" +
	"\treel_data\x18\x02 \x01(\v2\x14.feedcommon.ReelDataR\breelData\"\x9d\x03\n" +
	"\bReelData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12-\n" +
	"\atracker\x18\x02 \x01(\v2\x13.feedcommon.TrackerR\atracker\x12'\n" +
	"\x05video\x18\x03 \x01(\v2\x11.feedcommon.VideoR\x05video\x12:\n" +
	"\fhero_catalog\x18\x04 \x01(\v2\x17.feedcommon.CatalogInfoR\vheroCatalog\x12:\n" +
	"\fcatalog_info\x18\x05 \x03(\v2\x17.feedcommon.CatalogInfoR\vcatalogInfo\x12\x1b\n" +
	"\tuser_name\x18\x06 \x01(\tR\buserName\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x1b\n" +
	"\tfeed_type\x18\b \x01(\tR\bfeedType\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x05R\tlikeCount\x12*\n" +
	"\x11profile_image_url\x18\n" +
	" \x01(\tR\x0fprofileImageUrl\x12\x10\n" +
	"\x03gif\x18\v \x01(\tR\x03gif\"T\n" +
	"\aTracker\x12\x1d\n" +
	"\n" +
	"tracker_id\x18\x01 \x01(\tR\ttrackerId\x12*\n" +
	"\x11is_product_result\x18\x02 \x01(\bR\x0fisProductResult\"L\n" +
	"\x05Video\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\x12&\n" +
	"\x0fthumb_nail_webp\x18\x02 \x01(\tR\rthumbNailWebp\"8\n" +
	"\vCatalogInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bhero_pid\x18\x02 \x01(\x05R\aheroPidB\x17Z\x15../feedcommonresponseb\x06proto3"

var (
	file_feedcommonresponse_response_proto_rawDescOnce sync.Once
	file_feedcommonresponse_response_proto_rawDescData []byte
)

func file_feedcommonresponse_response_proto_rawDescGZIP() []byte {
	file_feedcommonresponse_response_proto_rawDescOnce.Do(func() {
		file_feedcommonresponse_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedcommonresponse_response_proto_rawDesc), len(file_feedcommonresponse_response_proto_rawDesc)))
	})
	return file_feedcommonresponse_response_proto_rawDescData
}

var file_feedcommonresponse_response_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_feedcommonresponse_response_proto_goTypes = []any{
	(*MetaData)(nil),       // 0: feedcommon.MetaData
	(*FeedResponse)(nil),   // 1: feedcommon.FeedResponse
	(*Entity)(nil),         // 2: feedcommon.Entity
	(*ReelViewSchema)(nil), // 3: feedcommon.ReelViewSchema
	(*ReelData)(nil),       // 4: feedcommon.ReelData
	(*Tracker)(nil),        // 5: feedcommon.Tracker
	(*Video)(nil),          // 6: feedcommon.Video
	(*CatalogInfo)(nil),    // 7: feedcommon.CatalogInfo
	(*CatalogView)(nil),    // 8: CatalogView
}
var file_feedcommonresponse_response_proto_depIdxs = []int32{
	2,  // 0: feedcommon.FeedResponse.entities:type_name -> feedcommon.Entity
	0,  // 1: feedcommon.FeedResponse.metadata:type_name -> feedcommon.MetaData
	8,  // 2: feedcommon.Entity.catalog_view:type_name -> CatalogView
	3,  // 3: feedcommon.Entity.reel_view:type_name -> feedcommon.ReelViewSchema
	8,  // 4: feedcommon.ReelViewSchema.catalog_view:type_name -> CatalogView
	4,  // 5: feedcommon.ReelViewSchema.reel_data:type_name -> feedcommon.ReelData
	5,  // 6: feedcommon.ReelData.tracker:type_name -> feedcommon.Tracker
	6,  // 7: feedcommon.ReelData.video:type_name -> feedcommon.Video
	7,  // 8: feedcommon.ReelData.hero_catalog:type_name -> feedcommon.CatalogInfo
	7,  // 9: feedcommon.ReelData.catalog_info:type_name -> feedcommon.CatalogInfo
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_feedcommonresponse_response_proto_init() }
func file_feedcommonresponse_response_proto_init() {
	if File_feedcommonresponse_response_proto != nil {
		return
	}
	file_feedcommonresponse_CatalogViewSchema_proto_init()
	file_feedcommonresponse_response_proto_msgTypes[2].OneofWrappers = []any{
		(*Entity_CatalogView)(nil),
		(*Entity_ReelView)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedcommonresponse_response_proto_rawDesc), len(file_feedcommonresponse_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedcommonresponse_response_proto_goTypes,
		DependencyIndexes: file_feedcommonresponse_response_proto_depIdxs,
		MessageInfos:      file_feedcommonresponse_response_proto_msgTypes,
	}.Build()
	File_feedcommonresponse_response_proto = out.File
	file_feedcommonresponse_response_proto_goTypes = nil
	file_feedcommonresponse_response_proto_depIdxs = nil
}
