sonar.organization=Meesho
sonar.projectKey=rv-iop
sonar.projectName=rv-iop
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.java.jdkHome=/usr/lib/jvm/java-17-openjdk-amd64/bin/java
sonar.go.coverage.reportPaths=./cov.out
sonar.coverage.exclusions=**/*_test.go,**/model.go,**/init.go,**/.pb.go,**/mock.go,**/internal/**,**/main.go